#ifndef __MTItemsListPanel__
#define __MTItemsListPanel__

/**
@file
Subclass of ItemsList, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"
#include <string>

//// end generated include

/** Implementing ItemsList */
class MTItemsListPanel : public ItemsList
{
protected:
	virtual void OnItemSelected(wxCommandEvent& event) override;
	public:
		/** Constructor */
		MTItemsListPanel( wxWindow* parent );
	//// end generated class members
	void	Totals(int totalItm, int totalGdm);
	void	AppendItemName(std::string &str);
	void	AppendItem();
	static int count;

};

#endif // __MTItemsListPanel__
