#pragma once
#ifndef MH4U_ITEM_LIST_HPP
#define MH4U_ITEM_LIST_HPP
#include <wx/arrstr.h>
#include <wx/string.h>

namespace MH4U
{
    const char* ITEMS[] = {
        "(None)",
        "Book of Combos 1",
        "Book of Combos 2",
        "Book of Combos 3",
        "Book of Combos 4",
        "Book of Combos 5",
        "Organizer Guide",
        "Pack Rat Guide",
        "Potion",
        "Mega Potion",
        "Nutrients",
        "Mega Nutrients",
        "Antidote",
        "Immunizer",
        "Dash Juice",
        "Mega Dash Juice",
        "Demondrug",
        "Mega Demondrug",
        "Might Pill",
        "Armorskin",
        "Mega Armorskin",
        "Adamant Pill",
        "Cool Drink",
        "Hot Drink",
        "Cleanser",
        "Deodorant",
        "Psychoserum",
        "Herbal Medicine",
        "Max Potion",
        "Ancient Potion",
        "Catalyst",
        "Energy Drink",
        "Gunpowder",
        "Lifecrystals",
        "Lifepowder",
        "Tranquilizer",
        "Mystery Charm",
        "Shining Charm",
        "Timeworn Charm",
        "Distorted Charm",
        "Powercharm",
        "Powertalon",
        "Armorcharm",
        "Armortalon",
        "Raw Meat",
        "Poisoned Meat",
        "Tinged Meat",
        "Drugged Meat",
        "Rare Steak",
        "Well-done Steak",
        "Burnt Meat",
        "Chilled Meat",
        "Hot Meat",
        "Mosswine Jerky",
        "Boomerang",
        "Throwing Knife",
        "Poison Knife",
        "Sleep Knife",
        "Paralysis Knife",
        "Tranq Knife",
        "Bomb Casing",
        "Paintball",
        "Flash Bomb",
        "Sonic Bomb",
        "Dung",
        "Dung Bomb",
        "Smoke Bomb",
        "Poison Smoke Bomb",
        "Farcaster",
        "Tranq Bomb",
        "Spider Web",
        "Net",
        "Trap Tool",
        "Pitfall Trap",
        "Shock Trap",
        "Small Barrel",
        "Large Barrel",
        "Barrel Bomb S",
        "Barrel Bomb S+",
        "Barrel Bomb L",
        "Barrel Bomb L+",
        "Bounce Bomb",
        "Bounce Bomb+",
        "Felvine Bomb",
        "Pirate Jump Bomb",
        "Huskberry",
        "Bone Husk",
        "Normal S Lv1",
        "Normal S Lv2",
        "Normal S Lv3",
        "Pierce S Lv1",
        "Pierce S Lv2",
        "Pierce S Lv3",
        "Pellet S Lv1",
        "Pellet S Lv2",
        "Pellet S Lv3",
        "Crag S Lv1",
        "Crag S Lv2",
        "Crag S Lv3",
        "Clust S Lv1",
        "Clust S Lv2",
        "Clust S Lv3",
        "Flaming S",
        "Water S",
        "Thunder S",
        "Freeze S",
        "Dragon S",
        "Poison S Lv1",
        "Poison S Lv2",
        "Para S Lv1",
        "Para S Lv2",
        "Sleep S Lv1",
        "Sleep S Lv2",
        "Exhaust S Lv1",
        "Exhaust S Lv2",
        "Slicing S",
        "WyvernFire",
        "Blast S",
        "Recover S Lv1",
        "Recover S Lv2",
        "Demon S",
        "Armor S",
        "Paint S",
        "Tranq S",
        "(No Coating)",
        "Empty Phial",
        "Power Coating",
        "C.Range Coating",
        "Poison Coating",
        "Para Coating",
        "Sleep Coating",
        "Exhaust Coating",
        "Blast Coating",
        "Paint Coating",
        "Power Nectar: Fire",
        "Stam Nectar: Water",
        "Spd Nectar: Thunder",
        "Speed Nectar: Ice",
        "Stam Nectar: Dragon",
        "Power+ Nectar",
        "Stamina+ Nectar",
        "Speed+ Nectar",
        "Nectar: Fire+",
        "Nectar: Water+",
        "Nectar: Thunder+",
        "Nectar: Ice+",
        "Nectar: Dragon+",
        "Power+ Nectar: Fire",
        "Stam+ Nectar: Water",
        "Spd+ Nectar: Thunder",
        "Power Nectar: Fire+",
        "Speed Nectar: Water+",
        "Spd Nectar: Thunder+",
        "Speed Nectar: Ice+",
        "Stam Nectar: Dragon+",
        "Worm",
        "Mega Fishing Fly",
        "Frog",
        "Sushifish Bait",
        "Burst Bait",
        "Goldenfish Bait",
        "Old Pickaxe",
        "Iron Pickaxe",
        "Mega Pickaxe",
        "Old Bug Net",
        "Bug Net",
        "Mega Bug Net",
        "BBQ Spit",
        "Whetstone",
        "Binoculars",
        "Garbage",
        "Field Horn",
        "Health Horn",
        "Antidote Horn",
        "Demon Horn",
        "Armor Horn",
        "Honey",
        "Herb",
        "Antidote Herb",
        "Fire Herb",
        "Ivy",
        "Sleep Herb",
        "Sap Plant",
        "Felvine",
        "Gloamgrass Root",
        "Hot Pepper",
        "Cathangea Seed",
        "Cathangea",
        "Cathangea Elixir",
        "Blue Mushroom",
        "Nitroshroom",
        "Parashroom",
        "Toadstool",
        "Exciteshroom",
        "Mopeshroom",
        "Dragon Toadstool",
        "Paintberry",
        "Might Seed",
        "Adamant Seed",
        "Nulberry",
        "Dragonfell Berry",
        "Scatternut",
        "Needleberry",
        "Latchberry",
        "Bomberry",
        "Bumblepumpkin",
        "Stone",
        "Iron Ore",
        "Earth Crystal",
        "Machalite Ore",
        "Dragonite Ore",
        "Lightcrystal",
        "Ice Crystal",
        "Firestone",
        "Gossamite Ore",
        "Heavenly Crystal",
        "Carbalite Ore",
        "Novacrystal",
        "Fucium Ore",
        "Firecell Stone",
        "Yoldspar Ore",
        "Abrasive",
        "Quality Abrasive",
        "Awesome Abrasive",
        "Armor Stone",
        "Armor Sphere",
        "Armor Sphere+",
        "Adv Armor Sphere",
        "Hard Armor Sphere",
        "Heavy Armor Sphere",
        "True Armor Sphere",
        "Whetfish",
        "Sushifish",
        "Sleepyfish",
        "Pin Tuna",
        "Speartuna",
        "Popfish",
        "Scatterfish",
        "Burst Arowana",
        "Bomb Arowana",
        "Glutton Tuna",
        "Gastronome Tuna",
        "Small Goldenfish",
        "Wanchovy",
        "Ancient Fish",
        "Blue Cutthroat",
        "Bronze Guild Ticket",
        "Silver Guild Ticket",
        "Insect Husk",
        "Gold Guild Ticket",
        "Stinkhopper",
        "Snakebee Larva",
        "Godbug",
        "Bitterbug",
        "Flashbug",
        "Thunderbug",
        "Glueglopper",
        "Killer Beetle",
        "Hercudrome",
        "Fulgurbug",
        "Rare Scarab",
        "Great Hornfly",
        "Butterfly Beetle",
        "Monster Bone S",
        "Monster Bone M",
        "Monster Bone L",
        "Mystery Bone",
        "Unknown Skull",
        "Monster Bone+",
        "Monster Keenbone",
        "Monster Hardbone",
        "Elder Dragon Bone",
        "Avian Finebone",
        "Brute Bone",
        "Jumbo Bone",
        "Stoutbone",
        "Dragonbone Relic",
        "Wyvern Fang",
        "Wyvern Claw",
        "Bird Wyvern Gem",
        "Wyvern Gem",
        "Elder Dragon Blood",
        "Steel Egg",
        "Silver Egg",
        "Golden Egg",
        "Slickaxe",
        "Screamer Sac",
        "Poison Sac",
        "Toxin Sac",
        "Paralysis Sac",
        "Sleep Sac",
        "Flame Sac",
        "Inferno Sac",
        "Electro Sac",
        "Thunder Sac",
        "Frost Sac",
        "Freezer Sac",
        "Aqua Sac",
        "Torrent Sac",
        "Dash Extract",
        "Pale Extract",
        "Gargwa Feather",
        "Kelbi Horn",
        "Blue Kelbi Horn",
        "Warm Pelt",
        "High-quality Pelt",
        "Rhenoplos Shell",
        "Rhenoplos Carapace",
        "Rhenoplos Scalp",
        "Slagtoth Hide",
        "Slagtoth Hide+",
        "Bnahabra Shell",
        "Bnahabra Carapace",
        "Bnahabra Wing",
        "Altaroth Jaw",
        "Altaroth Stomach",
        "Quality Stomach",
        "Sharp Fang",
        "Konchu Shell",
        "Konchu Carapace",
        "Remobra Hide",
        "Remobra Hide+",
        "Striped Skin",
        "Remobra Head",
        "Jaggi Scale",
        "Jaggi Scale+",
        "Jaggi Hide",
        "Bird Wyvern Fang",
        "Tough Bird Wyv Hide",
        "G.Jaggi Hide",
        "G.Jaggi Hide+",
        "G.Jaggi Claw",
        "G.Jaggi Claw+",
        "King's Frill",
        "Great Jaggi Head",
        "Velociprey Scale",
        "Velociprey Scale+",
        "Velociprey Hide",
        "Velociprey Hide+",
        "Velocidrome Hide",
        "Velocidrome Claw",
        "Velocidrome Claw+",
        "Velocidrome Head",
        "Genprey Fang",
        "Genprey Scale",
        "Genprey Scale+",
        "Genprey Hide",
        "Genprey Hide+",
        "Gendrome Hide",
        "Gendrome Tail",
        "Gendrome Head",
        "Ioprey Fang",
        "Ioprey Scale",
        "Ioprey Scale+",
        "Ioprey Hide",
        "Ioprey Hide+",
        "Iodrome Hide",
        "Iodrome Head",
        "Lagombi Pelt",
        "Lagombi Pelt+",
        "Lagombi Ear",
        "Lagombi Ear+",
        "Lagombi Plastron",
        "Lagombi Plastron+",
        "Lagombi Iceclaw",
        "Lagombi Frozenclaw",
        "Kut-Ku Scale",
        "Kut-Ku Scale+",
        "Kut-Ku Shell",
        "Kut-Ku Carapace",
        "Kut-Ku Ear",
        "Kut-Ku Auricle",
        "Giant Beak",
        "Splendid Beak",
        "Kut-Ku Webbing",
        "Invalid Message",
        "Blue Kut-Ku Scale+",
        "Blue Kut-Ku Carapace",
        "Rubbery Hide",
        "Rubbery Hide+",
        "Gypceros Head",
        "Rubbery Purple Hide",
        "P.Gypceros Wing",
        "Garuga Scale",
        "Garuga Scale+",
        "Garuga Shell",
        "Garuga Carapace",
        "Garuga Ear",
        "Garuga Auricle",
        "Sharpened Beak",
        "Rejuvenated Beak",
        "Garuga Wing",
        "Garuga Tail",
        "Garuga Mane",
        "Kecha Pelt",
        "Kecha Pelt+",
        "Kecha Longbone",
        "Kecha Grandbone",
        "Kecha Talon",
        "Kecha Ear",
        "Kecha Ear+",
        "Kecha Tail",
        "Conga Pelt",
        "Conga Pelt+",
        "Sharp Claw",
        "Congalala Pelt",
        "Congalala Pelt+",
        "Vibrant Pelt",
        "Congalala Claw",
        "Congalala Claw+",
        "Congalala Fang",
        "E.Congalala Pelt+",
        "E.Congalala Fang+",
        "E.Congalala Claw+",
        "Rajang Horn+",
        "Rajang Fang+",
        "Rajang Blackfur",
        "Rajang Claw+",
        "Rajang Tail",
        "Gold Rajang Pelt",
        "Rajang Ragehair",
        "Rajang Nerve",
        "Ghoulish Gold Horn",
        "Tetsucabra Scale",
        "Tetsucabra Scale+",
        "Tetsucabra Shell",
        "Tetsucabra Carapace",
        "Tetsucabra Claw",
        "Tetsucabra Claw+",
        "Tetsucabra Tusks",
        "Tetsucabra Tusks+",
        "Dignified Skull",
        "Paddock Oil",
        "Paddock Oil+",
        "Sharqskin Scale",
        "Meaty Hide",
        "Meaty Hide+",
        "Zamtrios Hide",
        "Zamtrios Hide+",
        "Zamtrios Scale",
        "Zamtrios Scale+",
        "Zamtrios Fin",
        "Zamtrios Fin+",
        "Zamtrios Sawtooth",
        "Zamtrios Tailblade",
        "Najarala Shell",
        "Najarala Carapace",
        "Najarala Hide",
        "Najarala Hide+",
        "Najarala Marrow",
        "Najarala Medulla",
        "Najarala Sounder",
        "Najarala Sounder+",
        "Najarala Fang",
        "Chilling Beak",
        "Nerscylla Shell",
        "Nerscylla Carapace",
        "Nerscylla Chelicera",
        "Nerscylla Shear",
        "Nerscylla Claw",
        "Nerscylla Sharpclaw",
        "Nerscylla Spike",
        "Nerscylla Spike+",
        "Monster Fluid",
        "Monster Broth",
        "Seltas Shell",
        "Seltas Carapace",
        "Seltas Wing",
        "Seltas Innerwing",
        "Seltas Horn",
        "Seltas Horn+",
        "S.Queen Shell",
        "S.Queen Carapace",
        "S.Queen Pectus",
        "S.Queen Hardpectus",
        "S.Queen Claw",
        "S.Queen Sharpclaw",
        "S.Queen Jaw",
        "S.Queen Crescent",
        "S.Queen Extract",
        "S.Queen Concentrate",
        "Flabby Hide",
        "Pearl Hide",
        "Pale Bone",
        "Pale Steak",
        "Alluring Hide",
        "Alluring Webbing",
        "Rathian Scale",
        "Rathian Scale+",
        "Rathian Shell",
        "Rathian Carapace",
        "Rathian Webbing",
        "Rathian Spike",
        "Rathian Spike+",
        "Rathian Plate",
        "Rathian Ruby",
        "P.Rathian Scale+",
        "P.Rathian Carapace",
        "G.Rathian Scale+",
        "G.Rathian Carapace",
        "G.Rathian Spike+",
        "Rathalos Scale",
        "Rathalos Scale+",
        "Rathalos Shell",
        "Rathalos Carapace",
        "Rathalos Webbing",
        "Rathalos Wing",
        "Rathalos Tail",
        "Rathalos Plate",
        "Rathalos Ruby",
        "A.Rathalos Scale+",
        "A.Rathalos Carapace",
        "A.Rathalos Tail",
        "A.Rathalos Wing",
        "S.Rathalos Scale+",
        "S.Rathalos Carapace",
        "S.Rathalos Tail",
        "Rath Wingtalon",
        "Rath Marrow",
        "Rath Medulla",
        "Rath Gleam",
        "Zinogre Shell",
        "Zinogre Carapace",
        "Zinogre Shockfur",
        "Zinogre Electrofur",
        "Zinogre Horn",
        "Zinogre Horn+",
        "Zinogre Claw",
        "Zinogre Claw+",
        "Zinogre Tail",
        "Zinogre Shocker",
        "Zinogre Shocker+",
        "Zinogre Plate",
        "Zinogre Jasper",
        "S.Zinogre Carapace",
        "S.Zinogre Horn+",
        "S.Zinogre Claw+",
        "S.Zinogre Tail",
        "S.Zin Drakeshell",
        "Dracophage Bug",
        "S.Zinogre Dragonhair",
        "S.Zinogre Umbrage",
        "Brach Shell",
        "Brach Carapace",
        "Brach Ebonshell",
        "Brach Ebonshell+",
        "Brach Scalp",
        "Brach Scalp+",
        "Mystery Slime",
        "Brach Hammer",
        "Brach Pounder",
        "Brach Tail",
        "Brach Marrow",
        "Brach Gem",
        "Basarios Shell",
        "Basarios Carapace",
        "Basarios Wing",
        "Basarios Tears",
        "R.Basarios Wing",
        "R.Basarios Carapace",
        "Gravios Shell",
        "Gravios Carapace",
        "Gravios Scalp",
        "Gravios Medulla",
        "Gravios Wing",
        "B.Gravios Carapace",
        "B.Gravios Scalp",
        "Tigrex Scale",
        "Tigrex Scale+",
        "Tigrex Shell",
        "Tigrex Carapace",
        "Tigrex Tail",
        "Tigrex Claw",
        "Tigrex Claw+",
        "Tigrex Fang",
        "Tigrex Fang+",
        "Tigrex Scalp",
        "Tigrex Maw",
        "B.Tigrex Scale+",
        "B.Tigrex Carapace",
        "B.Tigrex Claw+",
        "B.Tigrex Fang+",
        "M.Tigrex Scale+",
        "M.Tigrex Carapace",
        "M.Tigrex Blastclaw",
        "M.Tigrex Fang+",
        "M.Tigrex Tail",
        "Pulsating Blastheart",
        "Gore Magala Scale",
        "Gore Magala Scale+",
        "Gore Magala Shell",
        "Gore Magala Carapace",
        "Gore Magala Wing",
        "Gore Magala Wing+",
        "Gore Magala Ripclaw",
        "Gore Magala Ripclaw+",
        "Gore Magala Tail",
        "Gore Magala Plate",
        "Gore Magala Nyctgem",
        "Gore Magala Feeler",
        "Gore Magala Feeler+",
        "Defiled Scale",
        "S.Magala Scale",
        "S.Magala Scale+",
        "S.Magala Shell",
        "S.Magala Carapace",
        "S.Magala Prismwing",
        "S.Magala Prismwing+",
        "S.Magala Caress",
        "S.Magala Caress+",
        "S.Magala Tail",
        "S.Magala Plate",
        "S.Magala Phosgem",
        "S.Magala Horn",
        "S.Magala Horn+",
        "Pure Scale",
        "Deviljho Scale",
        "Deviljho Hide",
        "Deviljho Tallfang",
        "Deviljho Talon",
        "Deviljho Scalp",
        "Deviljho Tail",
        "Deviljho Saliva",
        "Black Blood",
        "Spattered Hide",
        "Deviljho Gem",
        "Kirin Thunderhorn",
        "Kirin Hide",
        "Kirin Hide+",
        "Kirin Mane",
        "Kirin Thundertail",
        "Kirin Azure Horn",
        "Kirin Icehorn",
        "Kirin Frost Tail",
        "Daora Scale",
        "Daora Carapace",
        "Daora Claw+",
        "Daora Tail",
        "Daora Webbing",
        "Daora Horn+",
        "Daora Gem",
        "Teostra Carapace",
        "Teostra Mane",
        "Teostra Tail",
        "Teostra Horn+",
        "Fire Dragon Scale+",
        "Teostra Claw+",
        "Teostra Webbing",
        "Teostra Powder",
        "Teostra Gem",
        "D.Mohran Shell",
        "D.Mohran Carapace",
        "D.Mohran Bloodscale",
        "D.Mohran Bloodscale+",
        "D.Mohran Brace",
        "D.Mohran Brace+",
        "Brutal Horn",
        "Brutal Horn+",
        "Dah'renstone",
        "Earth Dragongem",
        "Akantor Scale+",
        "Akantor Carapace",
        "Akantor Tail",
        "Akantor Hardclaw",
        "Akantor Tallfang",
        "Akantor Spike",
        "Akantor Gem",
        "Fatalis Horn",
        "Fatalis Scale",
        "Fatalis Shell",
        "Fatalis Eye",
        "Fatalis Webbing",
        "Fatalis Bloodhorn",
        "Fatalis Bloodscale",
        "Fatalis Bloodshell",
        "Fatalis Devileye",
        "Fatalis Bloodwing",
        "Dalamadur Steel",
        "Dalam Tail Scale",
        "Dalamadur Gazer",
        "Dalamadur Pectus",
        "Dalamadur Glaive",
        "Dalamadur Talon",
        "Dalam Tail Shell",
        "Dalamadur Fanblade",
        "Vortex Bone",
        "Skyblade Gem",
        "Shattered Omen",
        "Frenzy Shard",
        "Frenzy Crystal",
        "Vile Frenzy Crystal",
        "Small Lobstershell",
        "Lobster Tail Fan",
        "Plesioth Scale",
        "Plesioth Fin",
        "Arzuros Shell",
        "Arzuros Pelt",
        "Royal Ludroth Claw",
        "Spongy Hide",
        "Vivid Feather",
        "Strange Beak",
        "Barroth Shell",
        "Barroth Scalp",
        "Nibelsnarf Hide",
        "Vivid Fluid",
        "Ceanataur Shell",
        "Ceanataur Pincer",
        "Uragaan Marrow",
        "Uragaan Scute",
        "Nargacuga Blackfur",
        "Nargacuga Marrow",
        "Nargacuga Cutwing",
        "Duramboros Mossplate",
        "Duramboros Horn",
        "Lavasioth Scale",
        "Lavasioth Fin",
        "Diablos Shell",
        "Majestic Horn",
        "Lao-Shan Shell",
        "Lao-Shan Claw",
        "Lao-Shan Horn",
        "Vespoid Innerwing",
        "Cephalos Fin+",
        "Cephalos Scale+",
        "Hermitaur Carapace",
        "Hermitaur Claw+",
        "Gobul Hide+",
        "Gobul Spike+",
        "Volvidon Carapace",
        "Amber Tusks+",
        "Barioth Pelt+",
        "Blangonga Pelt+",
        "Blangonga Whisker",
        "Blangonga Fang+",
        "Shell Shocker+",
        "Lagiacrus Sapphire",
        "Agnaktor Carapace",
        "Agnaktor Fin+",
        "Lunastra Carapace",
        "Lunastra Mane",
        "Chameleos Hide+",
        "Chameleos Gem",
        "Chameleos Tail",
        "Tsukami Fluid",
        "Dragonwood+",
        "Dragonmoss+",
        "Ukanlos Shoveljaw",
        "Ukanlos Carapace",
        "Ukanlos Gem",
        "Gaoren Pincer",
        "Gaoren Thoracic",
        "Gaoren Claw+",
        "Ceadeus Hide",
        "Crooked Horn",
        "Luminous Organ",
        "Alatreon Plate",
        "Alatreon Webbing",
        "Skypiercer",
        "Rustshard",
        "Ancient Shard",
        "Rusted Fragment",
        "Ancient Fragment",
        "Battered Weapon",
        "Battered Armor",
        "Seasoned Weapon",
        "Seasoned Armor",
        "Venerable Weapon",
        "Venerable Armor",
        "Map",
        "First-aid Med",
        "First-aid Med+",
        "Ration",
        "Portable Spit",
        "Mini Whetstone",
        "EZ Shock Trap",
        "EZ Flash Bomb",
        "EZ Sonic Bomb",
        "EZ Max Potion",
        "EZ Pitfall Trap",
        "EZ Barrel Bomb L",
        "Ballista Ammo",
        "Ballista Binder",
        "One-shot Binder",
        "Cannon Ammo",
        "Anti-dragon Bomb",
        "Torch",
        "Paw Pass Ticket",
        "Unique Mushroom",
        "Choice Mushroom",
        "Ripened Mushroom",
        "Goldenfish",
        "Silverfish",
        "Royal Rhino",
        "Sulfur Crystal",
        "Auristone Chunk",
        "Crystal Bone",
        "Bloodstone",
        "Coal",
        "Fossilized Bone",
        "Mistentoe",
        "Decayed Scale",
        "Tiny Spall",
        "Lucky Spall",
        "Miracle Spall",
        "White Liver",
        "Slagtoth Oil",
        "Secret Stash",
        "Round Acorn",
        "Fine Stomach",
        "Luminous Stomach",
        "Monster Guts",
        "Popo Tongue",
        "Gargwa Egg",
        "Gold Gargwa Egg",
        "Wyvern Egg",
        "Herbivore Egg",
        "Sootstone Ore",
        "Powderstone",
        "Gargwa Guano",
        "Territorial Dung",
        "Territorial Dung+",
        "Drone Substance",
        "Queen Substance",
        "Toad Tear",
        "Large Toad Tear",
        "Wyvern Tear",
        "Large Wyvern Tear",
        "Beast Tear",
        "Large Beast Tear",
        "Dragon Treasure",
        "Old Dragon Treasure",
        "Pinnacle Coin",
        "Hunter King Coin",
        "Ace Hunter Coin",
        "Beast Coin",
        "Flying Coin",
        "Bird Coin",
        "Fang Coin",
        "Brute Coin",
        "Vermin Coin",
        "Toad Coin",
        "Invalid Message",
        "Voucher",
        "Gourmet Voucher",
        "Studio Pass",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "Fan Club Invite",
        "Monqlo Ticket",
        "Gold Studio Pass",
        "Platinum Pass",
        "dummy",
        "Amulet Keepsake",
        "dummy",
        "dummy",
        "Interpol Badge",
        "Val Habar Ticket",
        "dummy",
        "Goddess's Melody",
        "Goddess's Embrace",
        "dummy",
        "Uniqlo Ticket",
        "dummy",
        "dummy",
        "dummy",
        "Anklet Memento",
        "dummy",
        "dummy",
        "dummy",
        "Fan Club Certificate",
        "Triforce",
        "Goddess's Fire",
        "Super Mushroom",
        "Invalid Message",
        "D.Mohran Ticket",
        "Invalid Message",
        "Dalamadur Ticket",
        "Rajang Ticket",
        "Gore Magala Ticket",
        "Viper & Toad Ticket",
        "Oroshi Kirin Ticket",
        "Commendation",
        "Commendation G",
        "Accolade",
        "Accolade G",
        "Caravan Ticket",
        "Palico Ticket",
        "Meownster Ticket",
        "Quester's Ticket",
        "Kushala Daora Ticket",
        "Teostra Ticket",
        "Pawprint Stamp",
        "VE Ticket",
        "VE Deluxe Ticket",
        "VE Bronze Ticket",
        "VE Silver Ticket",
        "VE Golden Ticket",
        "Humble Scrap",
        "Handsome Scrap",
        "Gargwa Scrap",
        "Arzuros Scrap",
        "Kecha Wacha Scrap",
        "Yian Kut-Ku Scrap",
        "Bnahabra Scrap",
        "Bulldrome Scrap",
        "Rhenoplos Scrap",
        "Great Jaggi Scrap",
        "Nerscylla Scrap",
        "Qurupeco Scrap",
        "Zamtrios Scrap",
        "Lagombi Scrap",
        "Tetsucabra Scrap",
        "Barroth Scrap",
        "Slagtoth Scrap",
        "Volvidon Scrap",
        "Tigrex Scrap",
        "Great Baggi Scrap",
        "Nibelsnarf Scrap",
        "Seltas Queen Scrap",
        "Uragaan Scrap",
        "Great Wroggi Scrap",
        "Diablos Scrap",
        "Rathian Scrap",
        "Khezu Scrap",
        "Duramboros Scrap",
        "Zinogre Scrap",
        "Nargacuga Scrap",
        "Rathalos Scrap",
        "Agnaktor Scrap",
        "Najarala Scrap",
        "Gore Magala Scrap",
        "Shagaru Magala Scrap",
        "Teostra Scrap",
        "Deviljho Scrap",
        "Akantor Scrap",
        "Alatreon Scrap",
        "Kushala Daora Scrap",
        "Ukanlos Scrap",
        "Kirin Scrap",
        "Gigginox Scrap",
        "Rajang Scrap",
        "Brach Scrap",
        "Barioth Scrap",
        "Amatsu Scrap",
        "Dah'ren Mohran Scrap",
        "Jhen Mohran Scrap",
        "Dalamadur Scrap",
        "Royal Ludroth Scrap",
        "Plesioth Scrap",
        "Lagiacrus Scrap",
        "Aquaglow Jewel",
        "Sunspire Jewel",
        "Bloodrun Jewel",
        "Lazurite Jewel",
        "Adamant Orb",
        "Antidote Jewel 1",
        "Antidote Jewel 2",
        "Paralysis Jwl 1",
        "Paralysis Jwl 2",
        "Pep Jewel 1",
        "Pep Jewel 2",
        "Steadfast Jwl 1",
        "Standfast Jwl 1",
        "Tracker Jewel 1",
        "Trekker Jewel 1",
        "Ninja Jewel 1",
        "Vitality Jewel 1",
        "Recovery Jewel 1",
        "Recovery Jewel 2",
        "Razor Jewel 1",
        "Razor Jewel 3",
        "Handicraft Jwl 2",
        "Handicraft Jwl 3",
        "Fencer Jewel 1",
        "Fencer Jewel 3",
        "Expert Jewel 1",
        "Expert Jewel 2",
        "Expert Jewel 3",
        "Grinder Jewel 1",
        "Ironwall Jewel 1",
        "Ironwall Jewel 2",
        "Shield Jewel 1",
        "Shield Jewel 2",
        "Quickload Jwl 1",
        "Quickload Jwl 2",
        "Absorber Jewel 1",
        "Absorber Jewel 3",
        "Forceshot Jwl 1",
        "Forceshot Jwl 3",
        "Pierce Jewel 1",
        "Pierce Jewel 3",
        "Pellet Jewel 1",
        "Pellet Jewel 3",
        "ShotPlus Jewel 1",
        "ShotPlus Jewel 2",
        "PiercePlus Jwl 1",
        "PelletPlus Jwl 1",
        "CragPlus Jewel 1",
        "ClustPlus Jwl 1",
        "Disabler Jewel 1",
        "Disabler Jewel 2",
        "Element Jewel 1",
        "Element Jewel 3",
        "Bombardier Jwl 1",
        "Hungerless Jwl 1",
        "Metabolism Jwl 1",
        "Attack Jewel 1",
        "Attack Jewel 2",
        "Attack Jewel 3",
        "Defense Jewel 1",
        "Defense Jewel 2",
        "Protection Jwl 1",
        "Asylum Jewel 1",
        "Earplug Jewel 1",
        "Earplug Jewel 3",
        "Alarm Jewel 1",
        "Friendship Jwl 1",
        "Friendship Jwl 2",
        "Transportr Jwl 1",
        "Fire Res Jewel 1",
        "Water Res Jwl 1",
        "Ice Res Jewel 1",
        "ThunderRes Jwl 1",
        "Dragon Res Jwl 1",
        "Heat Res Jewel 1",
        "Cold Res Jewel 1",
        "Wind Res Jewel 1",
        "Wind Res Jewel 2",
        "Gathering Jwl 1",
        "Spree Jewel 1",
        "Blessing Jewel 1",
        "Fate Jewel 1",
        "Fate Jewel 3",
        "Psychic Jewel 1",
        "Medicine Jewel 1",
        "Medicine Jewel 2",
        "Professor Jwl 1",
        "Factory Jewel 1",
        "Evasion Jewel 1",
        "Evasion Jewel 2",
        "Potential Jwl 1",
        "Potential Jwl 2",
        "Enduring Jewel 1",
        "Sprinter Jewel 1",
        "Sprinter Jewel 3",
        "Capacity Jewel 2",
        "Capacity Jewel 3",
        "Sniper Jewel 1",
        "Gobbler Jewel 1",
        "Gobbler Jewel 3",
        "Carver Jewel 1",
        "Carver Jewel 3",
        "Footing Jewel 1",
        "Tectonic Jewel 1",
        "Jumping Jewel 1",
        "Draw Jewel 1",
        "Draw Jewel 2",
        "Trapmaster Jwl 1",
        "Physique Jewel 1",
        "Physique Jewel 2",
        "Capture Jewel 1",
        "Capture Jewel 3",
        "Perception Jwl 1",
        "Charger Jewel 1",
        "Charger Jewel 3",
        "Gambit Jewel 1",
        "Gambit Jewel 3",
        "Resistor Jewel 1",
        "Release Jewel 2",
        "Catalyst Jewel 3",
        "Fortitude Jwl 1",
        "Fortitude Jwl 2",
        "Salvo Jewel 1",
        "Salvo Jewel 3",
        "Torchlight Jwl 1",
        "Def Lock Jewel 1",
        "Blaze Jewel 1",
        "Blaze Jewel 2",
        "Stream Jewel 1",
        "Stream Jewel 2",
        "Bolt Jewel 1",
        "Bolt Jewel 2",
        "Frost Jewel 1",
        "Frost Jewel 2",
        "Dragon Jewel 1",
        "Dragon Jewel 2",
        "Tenderizer Jwl 1",
        "Tenderizer Jwl 3",
        "Destroyer Jwl 1",
        "Destroyer Jwl 3",
        "Throttle Jewel 1",
        "Throttle Jewel 2",
        "KO Jewel 1",
        "Drain Jewel 1",
        "Drain Jewel 2",
        "Sonorous Jewel 1",
        "Artillery Jwl 1",
        "Resistor Jewel 3",
        "Nul-Fire Jewel 1",
        "Nul-Water Jwl 1",
        "Nul-Thundr Jwl 1",
        "Nul-Ice Jewel 1",
        "Nul-Dragon Jwl 1",
        "Sheath Jewel 1",
        "Sheath Jewel 2",
        "Refresh Jewel 1",
        "Refresh Jewel 2",
        "Ranger Jewel 1",
        "SlicePlus Jwl 1",
        "Paracoat Jewel 1",
        "Paracoat Jewel 2",
        "Sleepcoat Jwl 1",
        "Poisoncoat Jwl 1",
        "Powercoat Jwl 1",
        "Powercoat Jwl 2",
        "Rangecoat Jwl 1",
        "Draincoat Jwl 1",
        "Guts Jewel 1",
        "Guts Jewel 2",
        "Meateater Jwl 1",
        "Meatlover Jwl 1",
        "Honeybee Jewel 1",
        "Queenbee Jewel 1",
        "Biology Jewel 1",
        "Microbio Jewel 1",
        "Spirit Jewel 1",
        "Spirit Jewel 2",
        "Flawless Jewel 1",
        "Flawless Jewel 2",
        "Steady Jewel 1",
        "Steady Jewel 3",
        "Player Jewel 1",
        "Morale Jewel 1",
        "Leader Jewel 1",
        "Leader Jewel 2",
        "KO Jewel 2",
        "Charmer Jewel 1",
        "BlastPlus Jwl 1",
        "Blastcoat Jwl 1",
        "Lynians",
        "Neopterons Vol 1",
        "Nerscylla",
        "Seltas Queen",
        "Piscine Wyverns Vol1",
        "Herbivores Vol 1",
        "Herbivores Vol 2",
        "Bird Wyverns Vol 1",
        "Bird Wyverns Vol 2",
        "Bird Wyverns Vol 3",
        "Fanged Beasts Vol 1",
        "Fanged Beasts Vol 2",
        "Fanged Beasts Vol 3",
        "Rajang",
        "Tetsucabra",
        "Zamtrios",
        "Snake Wyverns Vol 1",
        "Brachydios",
        "Deviljho",
        "Flying Wyverns Vol 1",
        "Flying Wyverns Vol 2",
        "Flying Wyverns Vol 3",
        "Flying Wyverns Vol 4",
        "Flying Wyverns Vol 5",
        "Flying Wyverns Vol 6",
        "Gore Magala",
        "Akantor",
        "Fanged Wyverns Vol 1",
        "Fanged Wyverns Vol 2",
        "Kirin",
        "Oroshi Kirin",
        "Shagaru Magala",
        "Dah'ren Mohran",
        "Kushala Daora",
        "Teostra",
        "Dalamadur",
        "Fatalis",
        "Honed Jwl 1",
        "Honed Jwl 2",
        "Honed Jwl 3",
        "True Honed Jwl 3",
        "Calm Jwl 1",
        "Calm Jwl 2",
        "Calm Jwl 3",
        "True Calm Jwl 3",
        "Hale Jwl 1",
        "Hale Jwl 2",
        "Hale Jwl 3",
        "True Hale Jwl 3",
        "Ire Jwl 1",
        "Ire Jwl 2",
        "Ire Jwl 3",
        "True Ire Jwl 3",
        "Nimble Jwl 1",
        "True Nimble Jwl 1",
        "Nimble Jwl 2",
        "Nimble Jwl 3",
        "True Nimble Jwl 3",
        "Hardy Jwl 1",
        "True Hardy Jwl 1",
        "Hardy Jwl 2",
        "Hardy Jwl 3",
        "True Hardy Jwl 3",
        "Withdrawn Jwl 1",
        "Withdrawn Jwl 3",
        "Impactful Jwl 1",
        "Impactful Jwl 3",
        "Intense Jwl 2",
        "Intense Jwl 3",
        "Aegis Jwl 2",
        "Aegis Jwl 3",
        "Tactful Jwl 2",
        "Tactful Jwl 3",
        "Broad Jwl 2",
        "Broad Jwl 3",
        "Trove Jwl 1",
        "True Trove Jwl 1",
        "Trove Jwl 2",
        "True Trove Jwl 2",
        "Trove Jwl 3",
        "Avid Jwl 1",
        "True Avid Jwl 1",
        "Avid Jwl 2",
        "True Avid Jwl 2",
        "Avid Jwl 3",
        "Power++ Nectar",
        "Stamina++ Nectar",
        "Speed++ Nectar",
        "Nectar: Fire++",
        "Nectar: Water++",
        "Nectar: Thunder++",
        "Nectar: Ice++",
        "Nectar: Dragon++",
        "Wystone Lv1: Brace",
        "Wystone Lv1: Element",
        "Wystone Lv1: Force",
        "Wystone Lv1: Drive",
        "Piscine Wyverns Vol2",
        "Herbivores Vol 3",
        "Carapaceons Vol 1",
        "Carapaceons Vol 2",
        "Neopterons Vol 2",
        "Neopterons Vol 3",
        "Flying Wyverns Vol 7",
        "Flying Wyverns Vol 8",
        "Seregios",
        "Fanged Beasts Vol 4",
        "Amphibians",
        "Snake Wyverns Vol 2",
        "dummy005",
        "Ukanlos",
        "Elder Dragons",
        "Gogmazios",
        "Coinperch S",
        "Coinperch M",
        "Coinperch L",
        "Cathangeafish Fry",
        "Cathangeafish",
        "Dundorma Tuna",
        "Temnocerans",
        "Rathian Shard",
        "Rathian Cortex",
        "Rathian Surspike",
        "Rathian Mantle",
        "Rath Wingtalon+",
        "P.Rathian Shard",
        "P.Rathian Cortex",
        "G.Rathian Shard",
        "G.Rathian Cortex",
        "G.Rath Surspike",
        "Firegleam Dollop",
        "Rathalos Shard",
        "Rathalos Cortex",
        "Rathalos Lash",
        "Rathalos Fellwing",
        "Rathalos Mantle",
        "A.Rathalos Shard",
        "A.Rathalos Cortex",
        "A.Rathalos Lash",
        "S.Rathalos Shard",
        "S.Rath Cortex",
        "S.Rath Lash",
        "Kut-Ku Shard",
        "Kut-Ku Cortex",
        "Kut-Ku Fellwing",
        "Kut-Ku Luckear",
        "Blue Kut-Ku Shard",
        "Blue Kut-Ku Cortex",
        "Garuga Shard",
        "Garuga Cortex",
        "Garuga Silverpelt",
        "Garuga Fellwing",
        "Garuga Lash",
        "Rubbery Finehide",
        "Gypceros Hardhead",
        "Rubbery Purple Hide+",
        "P.Gypceros Fellwing",
        "Tigrex Shard",
        "Tigrex Cortex",
        "Tigrex Hardfang",
        "Tigrex Hardclaw",
        "Tigrex Lash",
        "Tigrex Mantle",
        "B.Tigrex Shard",
        "B.Tigrex Cortex",
        "B.Tigrex Hardfang",
        "B.Tigrex Hardclaw",
        "M.Tigrex Shard",
        "M.Tigrex Cortex",
        "M.Tigrex Hardfang",
        "M.Tigrex Trigger",
        "M.Tigrex Lash",
        "Dire Blastheart",
        "Ioprey Piel",
        "Velocidrome Hardclaw",
        "Congalala Fur",
        "Congalala Hardclaw",
        "Beastly Fang",
        "E.Congalala Fur",
        "E.Congalala Hardclaw",
        "Vibrant Comb",
        "Rajang Wildpelt",
        "Rajang Hardhorn",
        "Rajang Hardfang",
        "Rajang Hardclaw",
        "Gold Rajang Pelt+",
        "Rajang Apoplexy",
        "Ghoulish Gold Gorer",
        "Rajang Heart",
        "Kecha Fur",
        "Kecha Leadbone",
        "Kecha Auricle",
        "Kecha Ripper",
        "Kecha Lash",
        "A.Kecha Fur",
        "A.Kecha Leadbone",
        "A.Kecha Auricle",
        "A.Kecha Ripper",
        "A.Kecha Lash",
        "Tetsucabra Shard",
        "Tetsucabra Cortex",
        "Tetsucabra Gnawrl",
        "Tetsucabra Hardclaw",
        "Vicious Visage",
        "B.Tetsucabra Shard",
        "B.Tetsucabra Cortex",
        "B.Tetsucabra Gnawrl",
        "B.TetsucabraHardclaw",
        "Zamtrios Shard",
        "Zamtrios Piel",
        "Zamtrios Grandfin",
        "Zamtrios Sawtooth+",
        "Zamtrios Tailbrand",
        "T.Zamtrios Shard",
        "T.Zamtrios Piel",
        "T.Zamtrios Grandfin",
        "T.Zamtrios Sawtooth+",
        "T.Zamtrios Tailbrand",
        "Najarala Piel",
        "Najarala Cortex",
        "Heart-stopping Beak",
        "Najarala Ampsounder",
        "T.Najarala Piel",
        "T.Najarala Cortex",
        "T.Najarala Splasher",
        "Dalamadur Steel+",
        "Dalamadur Glaive+",
        "Dalamadur Pectus+",
        "Dalamadur Ripper",
        "Dalamadur Fanblade+",
        "Dalam Tail Scale+",
        "Dalam Tail Shell+",
        "Skyblade Drgnsphire",
        "S.Dalamadur Steel+",
        "S.Dalamadur Glaive+",
        "S.Dalamadur Gazer",
        "S.Dalamadur Pectus+",
        "S.Dalamadur Ripper",
        "S.Dalam Fanblade+",
        "S.Dalam Tail Scale+",
        "S.Dalam Tail Shell+",
        "Seltas Cortex",
        "Seltas Razorwing",
        "Seltas Hardhorn",
        "D.Seltas Cortex",
        "D.Seltas Razorwing",
        "D.Seltas Hardhorn",
        "S.Queen Cortex",
        "S.Queen Pectus+",
        "S.Queen Maw",
        "S.Queen Hardclaw",
        "S.Queen Moonlash",
        "D.S.QueenConcentrate",
        "D.S.Queen Cortex",
        "D.S.Queen Pectus+",
        "D.S.Queen Maw",
        "D.S.Queen Hardclaw",
        "D.S.Queen Moonlash",
        "Nerscylla Cortex",
        "Nerscylla Scishorn",
        "Nerscylla Hardclaw",
        "Nerscylla Surspike",
        "S.Nerscylla Cortex",
        "S.Nerscylla Scishorn",
        "S.Nerscylla Hardclaw",
        "S.Nerscylla Surspike",
        "Gore Magala Shard",
        "Gore Magala Cortex",
        "Gore Magala Sensor",
        "Gore Magala Shredder",
        "Gore Magala Eclipse",
        "Gore Magala Lash",
        "Gore Magala Mantle",
        "Chaos Scale",
        "Diametrical Horn",
        "Antinomic Wing",
        "Contrary Scale",
        "S.Magala Shard",
        "S.Magala Cortex",
        "S.Magala Hardhorn",
        "S.Magala Purifier",
        "S.Magala Lightwing",
        "S.Magala Lash",
        "S.Magala Mantle",
        "Daora Cortex",
        "Daora Hardhorn",
        "Daora Fellwing",
        "Daora Lash",
        "Daora Shard",
        "Daora Hardclaw",
        "Steelrust Drakeshell",
        "Silverpeak Corona",
        "Steelrust Claw",
        "Maelstriker Wing",
        "Steelrust Scale",
        "Flame Shard",
        "Teostra Cortex",
        "Teostra Hardhorn",
        "Fire Dragon Hardclaw",
        "Teostra Lash",
        "Akantor Shard",
        "Akantor Cortex",
        "Akantor Greatfang",
        "Akantor Shredtalon",
        "Akantor Thickspike",
        "Akantor Flail",
        "Conquest Sphere",
        "Kirin Finehide",
        "Kirin Azure Peak",
        "Platinum Mane",
        "Kirin Thunderlash",
        "Kirin Ice Peak",
        "Kirin Frostlash",
        "Pearl Glosshide",
        "Khezu Special Cut",
        "Alluring Glosshide",
        "Alluring Fellwing",
        "Basarios Cortex",
        "Basarios Fellwing",
        "R.Basarios Cortex",
        "R.Basarios Fellwing",
        "Gravios Cortex",
        "Gravios Crown",
        "Gravios Fellwing",
        "Gravios Pallium",
        "B.Gravios Cortex",
        "B.Gravios Crown",
        "B.Gravios Pallium",
        "Deviljho Shard",
        "Deviljho Blackpiel",
        "Deviljho Hardfang",
        "Deviljho Ripper",
        "Deviljho Flail",
        "Deviljho Crook",
        "Bloodied Ebonhide",
        "Vile Fang",
        "Brach Cortex",
        "Fine Brach Ebonshell",
        "Brach Crown",
        "Brach Pounder+",
        "Brach Lash",
        "Brach Pallium",
        "Glowing Slime",
        "dummy006",
        "dummy007",
        "dummy008",
        "dummy009",
        "dummy010",
        "dummy011",
        "D.Mohran Rockskin",
        "D.Mohran Heavyscale",
        "Brutal Biter",
        "D.Mohran Allbrace",
        "Earth Dragonsphire",
        "Lagombi Fur",
        "Lagombi Auricle",
        "Zinogre Electrofur+",
        "Zinogre Cortex",
        "Zinogre Hardhorn",
        "Zinogre Hardclaw",
        "Zinogre D-Shocker",
        "Zinogre Lash",
        "Zinogre Skymerald",
        "S.Zin Dragonlocks",
        "S.Zinogre Cortex",
        "S.Zinogre Hardhorn",
        "S.Zinogre Hardclaw",
        "S.Zinogre Drakehold",
        "S.Zinogre Lash",
        "S.Zinogre Skymerald",
        "Seregios Slavescale",
        "Seregios Slavescale+",
        "Seregios Airblade",
        "Seregios Airblade+",
        "Seregios Carver",
        "Seregios Carver+",
        "Seregios Impaler",
        "Seregios Impaler+",
        "Seregios Breacher",
        "Seregios Breacher+",
        "Seregios Scraper",
        "Seregios Scraper+",
        "Seregios Dissenter",
        "Seregios Lens",
        "Gogmazios Battlement",
        "Gogmazios Fortress",
        "Gogmazios Gasher",
        "Gogmazios Offenders",
        "Gogmazios Fiberwing",
        "Gogmazios Briartail",
        "Wartorn Dragonsphire",
        "Heavy Drakesbone Oil",
        "Diablos Cortex",
        "Diablos Chine",
        "Twisted Stouthorn",
        "Diablos Hardhorn",
        "Diablos Tailcase+",
        "Blos Medulla",
        "B.Diablos Cortex",
        "B.Diablos Chine",
        "Blackcurl Stouthorn",
        "Monoblos Carapace",
        "Monoblos Cortex",
        "Monoblos Thoracic",
        "Monoblos Chine",
        "Scarlet Finehorn",
        "Scarlet Stouthorn",
        "Monoblos Heart",
        "W.Monoblos Cortex",
        "W.Monoblos Chine",
        "Argent Stouthorn",
        "Hermitaur Cortex",
        "Hermitaur Hardclaw",
        "Black Pearl",
        "Fine Black Pearl",
        "Wyvern Scalp",
        "Hermitaur Purpshell",
        "Hermitaur Purpclaw",
        "Cephalos Shard",
        "Cephalos Purpscale",
        "Cephalos Grandfin",
        "Cephalos Pinkfin",
        "Cephalos Fang+",
        "Cephalos Hardfang",
        "Piscine Liver",
        "Ukanlos Cortex",
        "Ukanlos Underscale",
        "Ukanlos Underscale+",
        "Ukanlos Tail",
        "Ukanlos Flail",
        "Ukanlos Digger",
        "Ukanlos Digger+",
        "Ukanlos Shoveljaw+",
        "Ukanlos Fin+",
        "Ukanlos Strongfin",
        "Ukanlos Stone",
        "Chameleos Finehide",
        "Chameleos Hardhorn",
        "Chameleos Fellwing",
        "Chameleos Lash",
        "Fatalis Shard",
        "Fatalis Cortex",
        "Fatalis Hardhorn",
        "Fatalis Evil Eye",
        "Fatalis Fellwing",
        "Fatalis Flamescale",
        "Fatalis Flameshell",
        "Fatalis Flamehorn",
        "Fatalis Flamewing",
        "Fatalis Devileye+",
        "Old Fatalis Shard",
        "Old Fatalis Cortex",
        "Old Fatalis Fellwing",
        "Old Fatalis Hardhorn",
        "Old Fatalis Souleye",
        "Deadly Poison Sac",
        "Conflagrant Sac",
        "Flood Sac",
        "Cryo Sac",
        "Lightning Sac",
        "Omniplegia Sac",
        "Coma Sac",
        "Fey Wyvern Gem",
        "Paddock Cream",
        "Lrg ElderDragon Bone",
        "Lrg Elder Dragon Gem",
        "Lrg Wyvern Gem",
        "Monster Slogbone",
        "Dragonbone Artifact",
        "Massive Bone",
        "Prized Pelt",
        "Rhenoplos Bone",
        "Avian Stoutbone",
        "Remobra Finehide",
        "Meaty Piel",
        "Crushing Fang",
        "Sml Hermitaur Shell",
        "Piercing Claw",
        "Bnahabra Razorwing",
        "Konchu Cortex",
        "Monster Essence",
        "Carapaceon Brains",
        "Carapaceon Brains+",
        "Crab Pearl",
        "Crab Pearl+",
        "Emperor Hopper",
        "Flutterfly",
        "Elder Bfly Beetle",
        "Great Elder Hornfly",
        "Divine Rhino",
        "Meteor Crystal",
        "Eltalite Ore",
        "Meldspar Ore",
        "Allfire Stone",
        "Purecrystal",
        "Cosmicite Ore",
        "Distorted Fragment",
        "Ultimate Abrasive",
        "Sovereign Orb",
        "Strong Armor Sphere",
        "Divine Armor Sphere",
        "Pure Frenzy Crystal",
        "Zenith Wyvern Gem",
        "Zenith Wyvern Gem L",
        "Enduring Charm",
        "Graven Charm",
        "Champion's Weapon",
        "Beshackled Weapon",
        "Champion's Armor",
        "Beshackled Armor",
        "Gloamgrass Bud",
        "Humble Scrap+",
        "Handsome Scrap+",
        "Gargwa Scrap+",
        "Arzuros Scrap+",
        "Rhenoplos Scrap+",
        "Great Jaggi Scrap+",
        "Bnahabra Scrap+",
        "Bulldrome Scrap+",
        "Slagtoth Scrap+",
        "Volvidon Scrap+",
        "Cephalos Scrap+",
        "Konchu Scrap+",
        "Kecha Wacha Scrap+",
        "Yian Kut-Ku Scrap+",
        "Tetsucabra Scrap+",
        "Barroth Scrap+",
        "Zamtrios Scrap+",
        "Lagombi Scrap+",
        "Uragaan Scrap+",
        "Rathian Scrap+",
        "Khezu Scrap+",
        "Great Wroggi Scrap+",
        "Congalala Scrap+",
        "Basarios Scrap+",
        "Nerscylla Scrap+",
        "Qurupeco Scrap+",
        "Nibelsnarf Scrap+",
        "Tigrex Scrap+",
        "Great Baggi Scrap+",
        "Rathalos Scrap+",
        "Agnaktor Scrap+",
        "Seltas Queen Scrap+",
        "Duramboros Scrap+",
        "Diablos Scrap+",
        "Rajang Scrap+",
        "Barioth Scrap+",
        "Brach Scrap+",
        "Zinogre Scrap+",
        "Nargacuga Scrap+",
        "Najarala Scrap+",
        "Seregios Scrap+",
        "Monoblos Scrap+",
        "Gravios Scrap+",
        "Yian Garuga Scrap+",
        "Gypceros Scrap+",
        "Dalamadur Scrap+",
        "Amatsu Scrap+",
        "S.Magala Scrap+",
        "Gore Magala Scrap+",
        "Kushala Daora Scrap+",
        "Ukanlos Scrap+",
        "Teostra Scrap+",
        "Deviljho Scrap+",
        "Kirin Scrap+",
        "Akantor Scrap+",
        "Alatreon Scrap+",
        "Dah'renMohran Scrap+",
        "Jhen Mohran Scrap+",
        "Gogmazios Scrap+",
        "Chameleos Scrap+",
        "Dust of Life",
        "Black Belt Coin G",
        "Expert Coin G",
        "Legend Coin G",
        "VE Cosmic Ticket",
        "Conqueror's Seal",
        "Conqueror's Seal G",
        "Caravan Ticket G",
        "Immenseness Ticket",
        "Immenseness Ticket S",
        "Proto Wystone: Drive",
        "Tropical Berry",
        "Portable Steam Bomb",
        "Disposable Earplugs",
        "Garrison Bllsta Ammo",
        "Dense Marcoal",
        "EZ Farcaster",
        "EZ Lifepowder",
        "EZ Dust of Life",
        "Meteor Chunk",
        "Frozen Berry",
        "Poogie Pearl",
        "Brach Warhead",
        "Brach Obliterator",
        "Immortal Reactor",
        "Flashpoint Slime",
        "G.Plesioth Shard",
        "Fine G.Plesioth Fin",
        "Gigginox Scrap+",
        "Royal Ludroth Scrap+",
        "Plesioth Scrap+",
        "Lagiacrus Scrap+",
        "Hermitaur Scrap+",
        "S.Barioth Sharpclaw",
        "J.Barroth Thoracic",
        "Qurupeco Shard",
        "Lustrous Feather",
        "C.Qurupeco Fellwing",
        "Gobul Piel",
        "Gobul Surspike",
        "Vespoid Razorwing",
        "Arzuros Cortex",
        "Nibelsnarf Cortex",
        "Dazzling Fluid",
        "Ceanataur Terraclaw",
        "Barioth Thickfur",
        "Heavy Amber Tusk",
        "Barroth Cortex",
        "Barroth Crown",
        "S.Barioth Hardclaw",
        "Volvidon Cortex",
        "Agnaktor Cortex",
        "Fine Agnaktor Fin",
        "J.Barroth Cortex",
        "Duramboros Cortex",
        "Duramboros Hardhorn",
        "Durambolite",
        "Uragaan Cortex",
        "Uragaan Pallium",
        "Nargacuga Blackfur+",
        "Nargacuga Cutwing+",
        "Nargacuga Mantle",
        "Lagiacrus Shard",
        "Deathly Shocker",
        "Lagiacrus Mantle",
        "I.Lagi D-Shocker",
        "I.Lagi Hardhorn",
        "Lavasioth Shard",
        "Fine Lavasioth Fin",
        "S.Uragaan Scute+",
        "Ceadeus Scale",
        "Ceadeus Strongfur",
        "Deep Dragongem",
        "Tsukami Fillet",
        "Ancient Dragonmoss",
        "Ancient Dragonwood",
        "Mohran Rockskin",
        "Mohran Allbrace",
        "Deific Fang",
        "Lunastra Cortex",
        "Lunastra Tail",
        "Lao-Shan Azure Claw",
        "Miralis Scale",
        "Miralis Smelter",
        "Dire Dragongem",
        "A.Lagi D-Shocker",
        "A.Lagi Dynamo",
        "L.Nargacuga Razor",
        "Cloudy Moonshard",
        "Lao-Shan Cortex",
        "Lao-Shan Shard",
        "Lao-Shan Mantle",
        "Amatsu Carapace",
        "Amatsu Webbing",
        "Heavenly Dragongem",
        "Alatreon Mantle",
        "Alatreon Riptalon",
        "Azure Dragonsphire",
        "Wystone Lv2: Brace",
        "Wystone Lv2: Element",
        "Wystone Lv2: Force",
        "Wystone Lv2: Drive",
        "Fardrake's Eye",
        "CritElementJwl 1",
        "CritElementJwl 2",
        "Crit Status Jwl 1",
        "Crit Status Jwl 2",
        "Precise Jewel 1",
        "Precise Jewel 2",
        "Fungiform Jewel 1",
        "Satiated Jewel 1",
        "Staunch Jewel 1",
        "Clean Jewel 1",
        "Rodeo Jewel 1",
        "Sane Jewel 1",
        "Sane Jewel 3",
        "Artisan Jewel 3",
        "Defense Jewel 3",
        "TrueCatalystJwl 3",
        "Cutting Jwl 1",
        "Cutting Jwl 2",
        "Cutting Jwl 3",
        "TrueCuttingJwl 3",
        "Arcane Jwl 1",
        "Arcane Jwl 2",
        "Arcane Jwl 3",
        "True Arcane Jwl 3",
        "Brawn Jwl 1",
        "Brawn Jwl 2",
        "Brawn Jwl 3",
        "True Brawn Jwl 3",
        "Supplicant Jwl 1",
        "Supplicant Jwl 2",
        "Supplicant Jwl 3",
        "Furtive Jwl 1",
        "Furtive Jwl 2",
        "Furtive Jwl 3",
        "TrueFurtiveJwl 3",
        "True Honed Jwl 2",
        "UltimateHonedJwl3",
        "True Calm Jwl 2",
        "UltimateCalmJwl 3",
        "True Hale Jwl 2",
        "UltimateHaleJwl 3",
        "True Ire Jwl 2",
        "UltimateIreJwl 3",
        "Withdrawn Jwl 2",
        "TrueWithdrawnJwl3",
        "Impactful Jwl 2",
        "TrueImpactfulJwl3",
        "TrueIntenseJwl 2",
        "TrueIntenseJwl 3",
        "True Aegis Jwl 2",
        "True Aegis Jwl 3",
        "TrueTactfulJwl 2",
        "TrueTactfulJwl 3",
        "True Broad Jwl 2",
        "True Broad Jwl 3",
        "dummy012",
        "Laden Jewel 3",
        "Daimyo Coin",
        "Argosy Ticket",
        "Yukumo Ticket",
        "Felcote Ticket",
        "Shakalaka Ticket",
        "Instructor's Ticket",
        "Guild Clerk Ticket",
        "Jumbo Ticket",
        "Hunter's Ticket",
        "Deviljho Ticket",
        "Amatsu Ticket",
        "Crimson Fatalis Ticket",
        "Wonderful Pass",
        "Special Pass",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "Clockwork Blueprint",
        "dummy",
        "Fan Club Newsletter",
        "Fan Club Cheer",
        "E-Tank",
        "Vintage Meat Ticket",
        "Fake Catalog",
        "Recruitment Poster",
        "Hero's Seal",
        "Design Pattern",
        "Weapon Data",
        "Defense Module",
        "The Tale of Poogie",
        "Goddess's Grace",
        "Gold Ring",
        "Festival Drum Music",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "dummy",
        "Proto Dense Marcoal",
        "Flying Coin G",
        "Brute Coin G",
        "Vermin Coin G",
        "Toad Coin G",
        "Snake Coin G",
        "Ace Ticket",
        "10,000 Zenny",
        "1,000 Caravan Points",
        "Jumping Jewel 2",
        "Live Bombfish",
        "Blue Marlin",
        "Horse Mackerel",
        "Pop-eyed Goldfish",
        "Giant Stag",
        "Darner Dragonfly",
        "Common Butterfly",
        "Flea",
        "EZ Marcoal",
        "(None)"
    };
    const wxArrayString wxITEMS(1937, ITEMS);

    const char* JEWELS[] = {
        "(None)",
        "Antidote Jewel 1",
        "Antidote Jewel 2",
        "Paralysis Jwl 1",
        "Paralysis Jwl 2",
        "Pep Jewel 1",
        "Pep Jewel 2",
        "Steadfast Jwl 1",
        "Standfast Jwl 1",
        "Tracker Jewel 1",
        "Trekker Jewel 1",
        "Ninja Jewel 1",
        "Vitality Jewel 1",
        "Recovery Jewel 1",
        "Recovery Jewel 2",
        "Razor Jewel 1",
        "Razor Jewel 3",
        "Handicraft Jwl 2",
        "Handicraft Jwl 3",
        "Artisan Jewel 3",
        "Fencer Jewel 1",
        "Fencer Jewel 3",
        "Expert Jewel 1",
        "Expert Jewel 2",
        "Expert Jewel 3",
        "Grinder Jewel 1",
        "Ironwall Jewel 1",
        "Ironwall Jewel 2",
        "Shield Jewel 1",
        "Shield Jewel 2",
        "Quickload Jwl 1",
        "Quickload Jwl 2",
        "Absorber Jewel 1",
        "Absorber Jewel 3",
        "Forceshot Jwl 1",
        "Forceshot Jwl 3",
        "Pierce Jewel 1",
        "Pierce Jewel 3",
        "Pellet Jewel 1",
        "Pellet Jewel 3",
        "ShotPlus Jewel 1",
        "ShotPlus Jewel 2",
        "PiercePlus Jwl 1",
        "PelletPlus Jwl 1",
        "CragPlus Jewel 1",
        "ClustPlus Jwl 1",
        "SlicePlus Jwl 1",
        "BlastPlus Jwl 1",
        "Disabler Jewel 1",
        "Disabler Jewel 2",
        "Element Jewel 1",
        "Element Jewel 3",
        "Bombardier Jwl 1",
        "Hungerless Jwl 1",
        "Metabolism Jwl 1",
        "Attack Jewel 1",
        "Attack Jewel 2",
        "Attack Jewel 3",
        "Defense Jewel 1",
        "Defense Jewel 2",
        "Defense Jewel 3",
        "Protection Jwl 1",
        "Asylum Jewel 1",
        "Earplug Jewel 1",
        "Earplug Jewel 3",
        "Alarm Jewel 1",
        "Friendship Jwl 1",
        "Friendship Jwl 2",
        "Transportr Jwl 1",
        "Fire Res Jewel 1",
        "Nul-Fire Jewel 1",
        "Water Res Jwl 1",
        "Nul-Water Jwl 1",
        "Ice Res Jewel 1",
        "Nul-Ice Jewel 1",
        "ThunderRes Jwl 1",
        "Nul-Thundr Jwl 1",
        "Dragon Res Jwl 1",
        "Nul-Dragon Jwl 1",
        "Heat Res Jewel 1",
        "Cold Res Jewel 1",
        "Wind Res Jewel 1",
        "Wind Res Jewel 2",
        "Gathering Jwl 1",
        "Spree Jewel 1",
        "Blessing Jewel 1",
        "Fate Jewel 1",
        "Fate Jewel 3",
        "Psychic Jewel 1",
        "Medicine Jewel 1",
        "Medicine Jewel 2",
        "Professor Jwl 1",
        "Factory Jewel 1",
        "Evasion Jewel 1",
        "Evasion Jewel 2",
        "Potential Jwl 1",
        "Potential Jwl 2",
        "Enduring Jewel 1",
        "Sprinter Jewel 1",
        "Sprinter Jewel 3",
        "Capacity Jewel 2",
        "Capacity Jewel 3",
        "Laden Jewel 3",
        "Sniper Jewel 1",
        "Gobbler Jewel 1",
        "Gobbler Jewel 3",
        "Carver Jewel 1",
        "Carver Jewel 3",
        "Footing Jewel 1",
        "Tectonic Jewel 1",
        "Jumping Jewel 1",
        "Jumping Jewel 2",
        "Draw Jewel 1",
        "Draw Jewel 2",
        "Trapmaster Jwl 1",
        "Physique Jewel 1",
        "Physique Jewel 2",
        "Capture Jewel 1",
        "Capture Jewel 3",
        "Perception Jwl 1",
        "Charger Jewel 1",
        "Charger Jewel 3",
        "Gambit Jewel 1",
        "Gambit Jewel 3",
        "Resistor Jewel 1",
        "Resistor Jewel 3",
        "Release Jewel 2",
        "Catalyst Jewel 3",
        "TrueCatalystJwl 3",
        "Fortitude Jwl 1",
        "Fortitude Jwl 2",
        "Salvo Jewel 1",
        "Salvo Jewel 3",
        "Torchlight Jwl 1 ",
        "Def Lock Jewel 1",
        "Blaze Jewel 1",
        "Blaze Jewel 2",
        "Stream Jewel 1",
        "Stream Jewel 2",
        "Bolt Jewel 1",
        "Bolt Jewel 2",
        "Frost Jewel 1",
        "Frost Jewel 2",
        "Dragon Jewel 1",
        "Dragon Jewel 2",
        "Tenderizer Jwl 1",
        "Tenderizer Jwl 3",
        "Destroyer Jwl 1",
        "Destroyer Jwl 3",
        "Throttle Jewel 1",
        "Throttle Jewel 2",
        "KO Jewel 1",
        "KO Jewel 2",
        "Drain Jewel 1",
        "Drain Jewel 2",
        "Sonorous Jewel 1",
        "Artillery Jwl 1",
        "Sheath Jewel 1",
        "Sheath Jewel 2",
        "Refresh Jewel 1",
        "Refresh Jewel 2",
        "Ranger Jewel 1",
        "Paracoat Jewel 1",
        "Paracoat Jewel 2",
        "Sleepcoat Jwl 1",
        "Poisoncoat Jwl 1",
        "Powercoat Jwl 1",
        "Powercoat Jwl 2",
        "Rangecoat Jwl 1",
        "Blastcoat Jwl 1",
        "Draincoat Jwl 1",
        "Guts Jewel 1",
        "Guts Jewel 2",
        "Meateater Jwl 1",
        "Meatlover Jwl 1",
        "Honeybee Jewel 1",
        "Queenbee Jewel 1",
        "Biology Jewel 1",
        "Microbio Jewel 1",
        "Spirit Jewel 1",
        "Spirit Jewel 2",
        "Flawless Jewel 1",
        "Flawless Jewel 2",
        "Steady Jewel 1",
        "Steady Jewel 3",
        "Player Jewel 1",
        "Morale Jewel 1",
        "Leader Jewel 1",
        "Leader Jewel 2",
        "Charmer Jewel 1",
        "Honed Jwl 1",
        "Honed Jwl 2",
        "Honed Jwl 3",
        "True Honed Jwl 3",
        "Calm Jwl 1",
        "Calm Jwl 2",
        "Calm Jwl 3",
        "True Calm Jwl 3",
        "Hale Jwl 1",
        "Hale Jwl 2",
        "Hale Jwl 3",
        "True Hale Jwl 3",
        "Ire Jwl 1",
        "Ire Jwl 2",
        "Ire Jwl 3",
        "True Ire Jwl 3",
        "Nimble Jwl 1",
        "True Nimble Jwl 1",
        "Nimble Jwl 2",
        "Nimble Jwl 3",
        "True Nimble Jwl 3",
        "Hardy Jwl 1",
        "True Hardy Jwl 1",
        "Hardy Jwl 2",
        "Hardy Jwl 3",
        "True Hardy Jwl 3",
        "Withdrawn Jwl 1",
        "Withdrawn Jwl 3",
        "Impactful Jwl 1",
        "Impactful Jwl 3",
        "Intense Jwl 2",
        "Intense Jwl 3",
        "Aegis Jwl 2",
        "Aegis Jwl 3",
        "Tactful Jwl 2",
        "Tactful Jwl 3",
        "Broad Jwl 2",
        "Broad Jwl 3",
        "Trove Jwl 1",
        "True Trove Jwl 1",
        "Trove Jwl 2",
        "True Trove Jwl 2",
        "Trove Jwl 3",
        "Avid Jwl 1",
        "True Avid Jwl 1",
        "Avid Jwl 2",
        "True Avid Jwl 2",
        "Avid Jwl 3",
        "CritElementJwl 1",
        "CritElementJwl 2",
        "Crit Status Jwl 1",
        "Crit Status Jwl 2",
        "Precise Jewel 1",
        "Precise Jewel 2",
        "Fungiform Jewel 1",
        "Satiated Jewel 1",
        "Staunch Jewel 1",
        "Clean Jewel 1",
        "Rodeo Jewel 1",
        "Sane Jewel 1",
        "Sane Jewel 3",
        "Cutting Jwl 1",
        "Cutting Jwl 2",
        "Cutting Jwl 3",
        "TrueCuttingJwl 3",
        "Arcane Jwl 1",
        "Arcane Jwl 2",
        "Arcane Jwl 3",
        "True Arcane Jwl 3",
        "Brawn Jwl 1",
        "Brawn Jwl 2",
        "Brawn Jwl 3",
        "True Brawn Jwl 3",
        "Supplicant Jwl 1",
        "Supplicant Jwl 2",
        "Supplicant Jwl 3",
        "Furtive Jwl 1",
        "Furtive Jwl 2",
        "Furtive Jwl 3",
        "TrueFurtiveJwl 3",
        "True Honed Jwl 2",
        "UltimateHonedJwl3",
        "True Calm Jwl 2",
        "UltimateCalmJwl 3",
        "True Hale Jwl 2",
        "UltimateHaleJwl 3",
        "True Ire Jwl 2",
        "UltimateIreJwl 3",
        "Withdrawn Jwl 2",
        "TrueWithdrawnJwl3",
        "Impactful Jwl 2",
        "TrueImpactfulJwl3",
        "TrueIntenseJwl 2",
        "TrueIntenseJwl 3",
        "True Aegis Jwl 2",
        "True Aegis Jwl 3",
        "TrueTactfulJwl 2",
        "TrueTactfulJwl 3",
        "True Broad Jwl 2",
        "True Broad Jwl 3"
    };
    const wxArrayString wxJEWELS(290, JEWELS);
}
#endif