#ifndef MH4U_MONSTER_LIST_HPP
#define MH4U_MONSTER_LIST_HPP

namespace MH4U
{
    const char *MONSTERS_LIST[] = {
        "None",
        "Rathian",
        "Rathalos",
        "Pink Rathian",
        "Azure Rathalos",
        "Gold Rathian",
        "Silver Rathalos",
        "Yian Kut-Ku",
        "Blue Yian Kut-Ku",
        "Gypceros",
        "Purple Gypceros",
        "Tigrex",
        "Brute Tigrex",
        "Gendrome",
        "Iodrome",
        "Great Jaggi",
        "Velocidrome",
        "Congalala",
        "Emerald Congalala",
        "Rajang",
        "Kecha Wacha",
        "Tetsucabra",
        "Zamtrios",
        "Najarala",
        "Dalamadur",
        "Seltas",
        "Seltas Queen",
        "Nerscylla",
        "Gore Magala",
        "Shagaru Magala",
        "Yian Garuga",
        "Kushala Daora",
        "Teostra",
        "Akantor",
        "Kirin",
        "Oroshi Kirin",
        "Khezu",
        "Red Khezu",
        "Basarios",
        "Ruby Basarios",
        "Gravios",
        "Black Gravios",
        "Deviljho",
        "Savage Deviljho",
        "Brachydios",
        "Rajang",
        "Dah'ren Mohran",
        "Lagombi",
        "Zinogre",
        "Stygian Zinogre",
        "Gargwa",
        "Rhenoplos",
        "Aptonoth",
        "Popo",
        "Slagtoth",
        "Red Slagtoth",
        "Jaggi",
        "Jaggia",
        "Velociprey",
        "Genprey",
        "Ioprey",
        "Remobra",
        "Delex",
        "Conga",
        "Kelbi",
        "Felyne",
        "Melynx",
        "Altaroth",
        "Bnahabra (Blue)",
        "Bnahabra (Yellow)",
        "Bnahabra (Green)",
        "Bnahabra (Red)",
        "Zamite",
        "Konchu (Yellow)",
        "Konchu (Green)",
        "Konchu (Blue)",
        "Konchu (Red)",
        "Fatalis",
        "Crimson Fatalis",
        "White Fatalis",
        "Molten Tigrex",
        "Rock (small rock)",
        "Rusted Kushala Daora",
        "Dalamadur",
        "Rock (slightly bigger rock)",
        "Rock (large molten rock)",
        "Rock (large invisible rock)",
        "Rock (anothet invisible rock)",
        "Seregios",
        "Gogmazios",
        "Ash Kecha Wacha",
        "Berserk Tetsucabra",
        "Tigerstripe Zamtrios",
        "Tidal Najarala",
        "Desert Seltas",
        "Desert Seltas Queen",
        "Shrouded Nerscylla",
        "Gore Magala",
        "Raging Brachydios",
        "Diablos",
        "Black Diablos",
        "Monoblos",
        "White Monoblos",
        "Chameleos",
        "Big Boulder",
        "Cephadrome",
        "Cephalos",
        "Daimyo Hermitaur",
        "Plum D.Hermitaur",
        "Hermitaur",
        "Shah Dalamadur",
        "Shah Dalamadur",
        "Apex Rajang",
        "Apex Deviljho",
        "Apex Zinogre",
        "Apex Gravios",
        "Ukanlos",
        "Flame Fatalis",
        "Apceros",
        "Apex Diablos",
        "Apex Tidal Najarala",
        "Apex Tigrex",
        "Apex Seregios",
        "(Reinforcement)"
    };
}

#endif