#pragma once
#include <wx/arrstr.h>

const char* WeaponBIAS[] = { 
	"S.Axe/C.Blade/I.Glaive",
	"Great Sword/Long Sword",
	"Sword & Shield/Dual Blades",
	"Lance/Gunlance",
	"Hammer/Hunting Horn",
	"Bow/Bowgun"
};

const char* ArmorBIAS[] = { 
	"Chest",
	"Arms",
	"Waist",
	"Legs",
	"Head"
};

const char* ArmorSeriesBIAS[] = { 
	"Original Series A",
	"Original Series B",
	"Original Series C",
	"Original Series D",
	"Original Series E",
	"Original Series F",
	"Tri Series A",
	"Tri Series B",
	"Tri Series C",
	"Tri Series D",
	"Tri Series E",
	"Tri Series F",
	"Freedom Series A",
	"Freedom Series B",
	"Freedom Series C",
	"Freedom Series D",
	"Freedom Series E",
	"Freedom Series F"
};

const char* QuestStars[] = { 
	"1*",
	"2*",
	"3*",
	"4*",
	"5*",
	"6*",
	"7*",
	"8*/G1",
	"9*/G2",
	"10*/G3",
	"11*",
	"12*",
	"13*",
	"14*"
}; wxArrayString wxQuestStars(14, QuestStars);

const char* QMaps[] = { 
	"Test Area",
	"Ancestal Steppe",
	"Sunken Hollow",
	"Primal Forest",
	"Frozen Seaway",
	"Heaven's Mount",
	"Great Desert",
	"Tower Summit",
	"Speartip Crag",
	"Ingle Isle",
	"Castle Schrade",
	"Arena",
	"Slayground",
	"Everwood",
	"Great Sea",
	"Volcanic Hollow",
	"Sanctuary",
	"Dunes (Day)",
	"Dunes (Night)",
	"Battlequarters",
	"Polar Field",
	"Great Sea(Storm)"
}; wxArrayString wxQMaps(22, QMaps);

const char* PlayerSpawn[] = { 
	"Base Camp",
	"Random",
	"Elder Dragon Fight"
}; wxArrayString wxPlayerSpawn(3, PlayerSpawn);

const char* Requirements[] = { 
	"None",
	"HR 2 or higher",
	"HR 3 or higher",
	"HR 4 or higher",
	"HR 5 or higher",
	"HR 6 or higher",
	"HR 7 or higher",
	"HR 8 or higher",
	"HR 10 or higher",
	"HR 20 or higher",
	"HR 50 or higher",
	"only Greatswords",
	"only Lances",
	"only Hammers",
	"only SnS",
	"only LBG or HBG",
	"only Dual Blades",
	"only Longsword",
	"only Gunlance",
	"only Hunting Horns",
	"only Bows",
	"only SwitchAxes",
	"only Insect Glaives",
	"only Charge Blades",
	"only Rare 1 Weapons",
	"no Armor/Charm",
	"no Items",
	"only 1 Player",
	"only 2 Players",
	"only 3 Players",
	"Palico needed",
	"no Palico",
	"G1-Permit",
	"G2-Permit",
	"G3-Permit",
	"G-Special-Permit",
	"G1/Rare 1/only Ammo"
}; wxArrayString wxReq(37, Requirements);

const char* Ranks[] = { 
	"None(?)",
	"Low Rank",
	"High Rank",
	"G Rank",
	"Arena"
}; wxArrayString wxRank(5, Ranks);

const char* MonsterAI[] = { 
	"Dumb",
	"Low Rank",
	"Low Rank+",
	"High Rank",
	"High Rank+",
	"G Rank",
	"GQ lvl 140"
}; wxArrayString wxMonsterAI(7, MonsterAI);

const char* QTypes[] = { 
	"Slay",
	"Capture",
	"Hunt",
	"Gathering",
	"Hunt All",
	"Slay All",
	"Capture All",
	"Gather All"
}; wxArrayString wxQTypes(8, QTypes);


const char* QIcons[] = { 
	"Question Mark",
	"Rathian",
	"Pink Rathian",
	"Gold Rathian",
	"Rathalos",
	"Azure Rathalos",
	"Silver Rathalos",
	"Yian Kut-Ku",
	"Blue Yian Kut-Ku",
	"Gypceros",
	"Purple Gypceros",
	"Tigrex",
	"Brute Tigrex",
	"Molten Tigrex",
	"Gendrome",
	"Iodrome",
	"Great Jaggi",
	"Velocidrome",
	"Congalala",
	"Emerald Congalala",
	"Rajang",
	"Furious Rajang",
	"Kecha Wacha",
	"Tetsucabra",
	"Zamtrios",
	"Najarala",
	"Seltas",
	"Seltas Queen",
	"Nerscylla",
	"Gore Magala",
	"Shagaru Magala",
	"Yian Garuga",
	"Kushala Daora",
	"Rusted Kushala Daora",
	"Teostra",
	"Akantor",
	"Kirin",
	"Oroshi Kirin",
	"Khezu",
	"Red Khezu",
	"Basarios",
	"Ruby Basarios",
	"Gravios",
	"Black Gravios",
	"Deviljho",
	"Savage Deviljho",
	"Brachydios",
	"Dah'ren Mohran",
	"Lagombi",
	"Zinogre",
	"Stygian Zinogre",
	"Gargwa",
	"Rhenoplos",
	"Aptonoth",
	"Popo",
	"Slagtoth",
	"Red Slagtoth",
	"Jaggi",
	"Jaggia",
	"Velociprey",
	"Genprey",
	"Ioprey",
	"Remobra",
	"Delex",
	"Conga",
	"Kelbi",
	"Feliyne",
	"Melynx",
	"Altaroth",
	"Bnahabra",
	"Zamite",
	"Konchu",
	"Dalamadur (Head)",
	"Dalamadur (Tail)",
	"(None)",
	"(None)",
	"(None)",
	"Thing",
	"Round Face",
	"(None)",
	"(None)",
	"(None)",
	"(None)",
	"(None)",
	"Danger",
	"Question Mark 2",
	"Treasure Chest",
	"Cross",
	"Frenzy",
	"Egg",
	"Rock",
	"Fish",
	"Bones",
	"Bug Net",
	"Mushroom",
	"Honey",
	"Harvest",
	"Dragon Emblem",
	"(None) default",
	"Seregios",
	"Ash Kecha Wacha",
	"Berserk Tetsukabra",
	"Tigerstripe Zamtrios",
	"Tidal Najarala",
	"Desert Seltas",
	"Desert Seltas Queen",
	"Shrouded Nerscylla",
	"Chaotic Gore Magala",
	"Raging Brachydios",
	"Diablos",
	"Black Diablos",
	"Monoblos",
	"White Monoblos",
	"Chameleos",
	"Cephadrome",
	"Cephalos",
	"Daimyo Hermitaur",
	"Plum Daimyo Hermitaur",
	"Hermitaur",
	"Ukanlos",
	"Apceros",
	"Shah Dalamadur (Head)",
	"Shah Dalamadur (Tail)",
	"Apex"
}; wxArrayString wxQIcons(124, QIcons);


/* LbMain // Lobby Main:
 * Guildmaster
 * Guild Store Clerk
 * Low Questatrix
 * High Questatrix
 * Arena Bambina
 * Gong Lady
 **/