#ifndef MH4U_SKILLS_LIST_HPP
#define MH4U_SKILLS_LIST_HPP
#include <wx/arrstr.h>

namespace MH4U
{
    const char *SKILLS_LIST[] = {
        "(None)",
        "Torso Up",
        "Edgemaster",
        "Steady Hand",
        "Status Res",
        "Fury",
        "Biology",
        "Nimbleness",
        "Readiness",
        "Resillience",
        "Brutality",
        "Ferocity",
        "Stalwart",
        "Prudence",
        "Amplifiy",
        "Hoarding",
        "Avarice",
        "FreeElemnt",
        "Fencing",
        "Handicraft",
        "Crit Draw",
        "PunishDraw",
        "Reload Spd",
        "Recoil",
        "Rapid Fire",
        "Gloves Off",
        "Spirit",
        "Unshakable",
        "Charmer",
        "Tenderizer",
        "Blight Res",
        "Attack",
        "Defense",
        "Gathering",
        "Carving",
        "Fate",
        "Tranqilzr",
        "Expert",
        "Artillery",
        "Evasion",
        "Health",
        "Hearing",
        "Sharpness",
        "Guard",
        "Guard Up",
        "Sharpener",
        "Potential",
        "Bomb Boost",
        "Status",
        "Stamina",
        "Destroyer",
        "Evade Dist",
        "Sheating",
        "FastCharge",
        "Stam Drain",
        "Unscathed",
        "Guts",
        "Loading",
        "Normal Up",
        "Pierce Up",
        "Pellet Up",
        "KO",
        "Def Lock",
        "LastingPwr",
        "Normal S+",
        "Pierce S+",
        "Pellet S+",
        "Crag S+",
        "Clust S+",
        "Slicing S+",
        "Blast S+",
        "Poison C+",
        "Para C+",
        "Sleep C+",
        "Power C+",
        "C.Range C+",
        "Exhaust C+",
        "Blast C+",
        "Precision",
        "Fire Atk",
        "Water Atk",
        "Thunder Atk",
        "Ice Atk",
        "Dragon Atk",
        "Elemental",
        "Fire Res",
        "Water Res",
        "Thunder Res",
        "Ice Res",
        "Dragon Res",
        "Spd Gather",
        "Psychic",
        "Perception",
        "Rec Level",
        "Wide-Range",
        "Maestro",
        "Survivor",
        "Carnivore",
        "Gluttony",
        "Constitutn",
        "Stam Recov",
        "Wind Res",
        "Eating",
        "Combo Rate",
        "Combo Plus",
        "Ranger",
        "Heat Res",
        "Cold Res",
        "Commander",
        "TeamPlayer",
        "TeamLeader",
        "RecSpeed",
        "Whim",
        "Protection",
        "Hunger",
        "Transportr",
        "SpeedSetup",
        "Honey",
        "Poison",
        "Paralysis",
        "Sleep",
        "Stun",
        "Mud/Snow",
        "Tremor Res",
        "Anti-Theft",
        "Sense",
        "Flame Aura",
        "Auto Guard",
        "Franzy Res",
        "Mounting",
        "CritElemnt",
        "CritStatus",
        "Dead Eye",
        "Mycology",
        "LightEater",
        "Bleeding",
        "Sticky Res",
        "Edge Lore",
        "PowerEater",
        "D. Fencing",
        "Arcana",
        "Mechanic",
        "Brawn",
        "Prayer",
        "Covert"
    }; const wxArrayString wxSKILLS_LIST(145, SKILLS_LIST);
}

#endif