#pragma once
#ifndef MH4U_WEAPONS
#define MH4U_WEAPONS
#include <wx/arrstr.h>

namespace MH4U
{
    const char *GS_LIST[] = {
        "(None)",
        "Iron Sword",
        "Iron Sword+",
        "Buster Sword",
        "Buster Sword+",
        "Ravager Blade",
        "Ravager Blade+",
        "Lacerator Blade",
        "Devistator Blade",
        "Chrome Razor",
        "Chrome Quietus",
        "Khezu Shock Sword",
        "Khezu Shock Blade",
        "Khezu Shock Full",
        "Santoku Reaver",
        "Funayuki Reaver",
        "Toad Bereaver",
        "Millstone Bereaver",
        "Blazenwall",
        "Crimsonwall",
        "Cragscliff",
        "Rugged Great Sword",
        "Chieftain's Great Sword",
        "Schattenstolz",
        "Düsterstolz",
        "Verhängnisstolz",
        "L'Apothéose",
        "Usurper's Storm",
        "Despot's Blackstorm",
        "Brimstren Drakepride",
        "Demon Rod",
        "Great Demon Rod",
        "Ludroth Bone Sword",
        "Ludroth Bone Sword+",
        "Cataclysm Sword",
        "Cataclysm Blade",
        "Bone Blade",
        "Bone Blade+",
        "Jawblade",
        "Giant Jawblade",
        "Golem Blade",
        "Tiger Jawblade",
        "Tigrex Great Sword",
        "Accursed Blade",
        "Veined Graveblade",
        "Dios Blade",
        "Dios Blade+",
        "Executioner",
        "Valkyrie Blade",
        "Sieglinde",
        "Titania",
        "Blushing Dame",
        "Auberon",
        "Red Wing",
        "Rathalos Firesword",
        "Rathalos Flamesword",
        "Rathalos Gleamsword",
        "Rathalos Glintsword",
        "Thrash Sword",
        "Thrash Sword+",
        "Thrash Blade",
        "Thrashgash Blade",
        "Immane Blade",
        "Immolator Blade",
        "Scylla Blade",
        "Scylla Razor",
        "Vile Serpentblade",
        "Vile Serpentblade+",
        "Fanged Serpentblade",
        "Deadly Serpentblade",
        "Poison Serpentblade",
        "Chick Decapitator",
        "Rooster Decapitator",
        "Sentoryu Raven",
        "Sentoryu Wolf",
        "Sentoryu Crow",
        "Hidden Blade",
        "Dark of Night",
        "Vulcanis",
        "Vulcamagnon",
        "Plesioth Watercutter",
        "Plesioth Watercutter+",
        "Plesioth Lullaby",
        "Plesioth Lullabane",
        "Frozen Speartuna",
        "Freezer Speartuna",
        "Rusted Great Sword",
        "Tarnished Great Swd",
        "Ancient Blade",
        "Elder Monument",
        "Icesteel Edge",
        "Daora's Decimator",
        "Worn Great Sword",
        "Weathered Great Swd",
        "Epitaph Blade",
        "Teostra Blade",
        "King Teostra Blade",
        "Kirin Thundersword",
        "King Thundersword",
        "Emperor Frostsword",
        "Berserker Sword",
        "Anguish",
        "Consummate Blade",
        "Akantor Broadsword",
        "Swordscale Shard",
        "The Lethal Graze",
        "Fatalis Blade",
        "dummy107",
        "dummy108",
        "dummy109",
        "dummy110",
        "dummy111",
        "dummy112",
        "dummy113",
        "Universal Chrome",
        "Siegmund (red)",
        "Siegmund (yellow)",
        "Siegmund (green)",
        "Siegmund (blue)",
        "Siegmund (purple)",
        "Bolt (red)",
        "Bolt (yellow)",
        "Bolt (green)",
        "Bolt (blue)",
        "Bolt (purple)",
        "Type 41 Wyvernator (red)",
        "Type 41 Wyvernator (yellow)",
        "Type 41 Wyvernator (green)",
        "Type 41 Wyvernator (blue)",
        "Type 41 Wyvernator (purple)",
        "Flash (red)",
        "Flash (yellow)",
        "Flash (green)",
        "Flash (blue)",
        "Flash (purple)",
        "Dragonseal (red)",
        "Dragonseal (yellow)",
        "Dragonseal (green)",
        "Dragonseal (blue)",
        "Dragonseal (purple)",
        "Exemplar Blade",
        "Grandglory Blade",
        "Chrome Hell",
        "Chrome Heaven",
        "Blood Sword",
        "Blood Shock",
        "Rampage Blade",
        "Rampage Temperline",
        "Cragscliff+",
        "Cliffsword Titanius",
        "L'Éclat",
        "L'Origine",
        "Düster/Éclat",
        "Oppressor's Forger",
        "Orcus Tonitrus",
        "Brimstren Drakepride+",
        "Stygian Acedia",
        "Great Demon Hot Rod",
        "Demonlord Rod",
        "Cataclysm Blade+",
        "Veined Graveblade+",
        "Deified Grisblade",
        "Myxo Demolisher",
        "Lightbreak Blade",
        "Executioner",
        "Executioner+",
        "Enforcer's Axe",
        "Cera Cigil",
        "Cera Cymmetry",
        "Red Pincer",
        "Great Pincer",
        "Violet Pincer",
        "Grand Pincer",
        "Blushing Dame+",
        "Brünnhilde",
        "Auberon+",
        "Pale Kaiser",
        "Rathalos Gleamsword+",
        "Rathlord Gleamsword",
        "Rathalos Glinsword+",
        "Rathflame Glinsword",
        "Jala Blade",
        "Jajala Blade",
        "Pavaka Blade",
        "Jvalayati Blade",
        "Scylla Shear",
        "Ebonscylla",
        "Webbonscylla",
        "Snakesmaw",
        "Sentoryu Pox",
        "Garuga Engetsu",
        "Dark of Night+",
        "Avidya Great Sword",
        "Vulcatastrophe",
        "Vulca Vendetta",
        "Plesioth Lullabane+",
        "Plesioth Pelagis",
        "Xiphias Gladius",
        "Eternal Glyph",
        "Daora's Deathmaker",
        "Eldaora's Death",
        "Epitaph Blade+",
        "Epitaph Eternal",
        "Teostra del Sol",
        "Grand Shamshir",
        "Emperor Thundersword",
        "Frostsword",
        "King Frostsword",
        "Doomedge Hrunting""",
        "Akantor Broadsword+",
        "Ukanlos Destructor",
        "Ukanlos Skycleaver",
        "Wold the Just",
        "Dalamadur Blade",
        "Dreaming Dalamadur",
        "Black Fatalis Blade",
        "Flame Fatalis Blade",
        "Fatalis Legacy",
        "Cheda Blade",
        "Cheda Blade+",
        "Seditious Cleaver",
        "Rogue Sedition",
        "Monument of Lament",
        "Ostracon Oblivion",
        "G Blade",
        "Black Belt Blade",
        "Commemoration Sword",
        "dummy227",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "Dos Exile",
        "Rath of Stars",
        "Sea-emperor's Sword (red)",
        "Sea-emperor's Sword (yellow)",
        "Sea-emperor's Sword (green)",
        "Sea-emperor's Sword (blue)",
        "Sea-emperor's Sword (purple)",
        "Jawblade (red)",
        "Jawblade (yellow)",
        "Jawblade (green)",
        "Jawblade (blue)",
        "Jawblade (purple)"
    }; const wxArrayString wxGS_LIST(246, GS_LIST);

    const char *SNS_LIST[] = {
        "(None)",
        "Hunter's Knife",
        "Hunter's Knife+",
        "Soldier's Dagger",
        "Commander's Dagger",
        "Deadly Knife",
        "Deadly Knife+",
        "Natch Knife",
        "Acclimated Knife",
        "Rebellious Knife",
        "Sucher-Ankh",
        "Jäger-Ankh",
        "Sieger-Ankh",
        "Le Détecteur",
        "Princess Rapier",
        "Queen Rapier",
        "Queen Rose",
        "Royal Rose",
        "Velocidrome Bite",
        "Velocidrome Bite+",
        "Velocidrome Fang",
        "Velocidrome Fang+",
        "Drome Rush Dagger",
        "Hydra Bite",
        "Spiked Circle",
        "Paraspiked Circle",
        "Usurper's Firebolt",
        "Despot's Crookbolt",
        "Brimstren Drakescale",
        "Lagia Sword",
        "High Lagia Sword",
        "Hunter's Dagger",
        "Assassin's Dagger",
        "Viper Bite",
        "Viper Bite+",
        "Deathprize",
        "Azi Dahaka",
        "Almighty Dahaka",
        "Poison Battleaxe",
        "Poison Battleaxe+",
        "Upper Battleaxe",
        "Deadly Battleaxe",
        "Frightbane",
        "Thor Indora",
        "Djinn",
        "Djinn+",
        "Blazing Falchion",
        "Golden Falchion",
        "Dios Edge",
        "Dios Edge+",
        "Demolition Cutter",
        "Bone Kris",
        "Bone Kris+",
        "Chief Kris",
        "Sharkutter",
        "Sharkutter+",
        "Sharlin Sword",
        "Sharfinisher",
        "Rex Talon",
        "Tigrex Sword",
        "Accursed Claw",
        "Roaring Gravesword",
        "Celestial Sword",
        "Celestial Arms",
        "Celestial Brand",
        "Cross Sword",
        "Extraordinary Cross",
        "Dual Cross Brand",
        "Flame Syphos",
        "Flame Syphos+",
        "Black Dorn Flame",
        "Scaly Sword",
        "Scaly Sword+",
        "Bloodscale Sword",
        "Bloodsquama Sword",
        "Ludroth Nail",
        "Royal Claw",
        "Odyssey",
        "Odyssey Blade",
        "Tusk Gear",
        "Skull's Wrath",
        "Catspaw",
        "Catspaw+",
        "Catburglar",
        "Plesioth Finspike",
        "Plesioth Finspike+",
        "Plesioth Direspike",
        "Hero Blade",
        "Master Blade",
        "Rusted Sword",
        "Tarnished Sword",
        "Eternal Strife",
        "Eternal Hate",
        "Steel Ice Dagger",
        "Daora's Razor",
        "Worn Sword",
        "Weathered Sword",
        "Divine Exodus",
        "Kirin Bolt",
        "Kirin Bolt Ultimus",
        "Kirin Ice Ultimus",
        "Poise",
        "Ame-no-habakiri",
        "Eviscerator & Scutum",
        "The Antimonial Haven",
        "Fatalis Sword",
        "Ruiner Sword",
        "dummy107",
        "Hero's Sword",
        "Master Sword",
        "EX Poise",
        "EX Ame-no-habakiri",
        "Jhen Kodachi (red)",
        "Jhen Kodachi (yellow)",
        "Jhen Kodachi (green)",
        "Jhen Kodachi (blue)",
        "Jhen Kodachi (purple)",
        "Chak Chak (red)",
        "Chak Chak (yellow)",
        "Chak Chak (green)",
        "Chak Chak (blue)",
        "Chak Chak (purple)",
        "Hidden Edge (red)",
        "Hidden Edge (yellow)",
        "Hidden Edge (green)",
        "Hidden Edge (blue)",
        "Hidden Edge (purple)",
        "Master Bang (red)",
        "Master Bang (yellow)",
        "Master Bang (green)",
        "Master Bang (blue)",
        "Master Bang (purple)",
        "Golden Falchion (red)",
        "Golden Falchion (yellow)",
        "Golden Falchion (green)",
        "Golden Falchion (blue)",
        "Golden Falchion (purple)",
        "Frost Edge (red)",
        "Frost Edge (yellow)",
        "Frost Edge (green)",
        "Frost Edge (blue)",
        "Frost Edge (purple)",
        "Rebellious Knife+",
        "Vengeful Knife",
        "Spiked Saber",
        "Clawed Saber",
        "Serevento",
        "La Vérité",
        "Le Limier",
        "Lügen/Vérité",
        "Royal Rose+",
        "Rose Highness",
        "Lunatic Rose",
        "Great Stabberdag",
        "Deadly Poison",
        "Paraspiked Rondo",
        "Paralyzing Rondo",
        "Lepis Prism",
        "Grootslang",
        "Brimstren Drakescale+",
        "Stygian Luxuria",
        "Neo Lagia Sword",
        "Neodignis Whitebolt",
        "Co Dolgan",
        "Coctura Balgang",
        "Gypcer Francisca",
        "Gypcer Francisca+",
        "Thor Rigindora",
        "Golden Radius",
        "Platinum Dawn",
        "Annular Sol",
        "Struxion Demolisher",
        "Lightbreak Sword",
        "Icy Akzar",
        "Zamtrista Akzar",
        "Agate Saw",
        "Zamtrista Saw",
        "Roaring Gravesword+",
        "Reigning Grissword",
        "Crimson Club",
        "Crimson Club+",
        "Monoblos Club",
        "Studded Club",
        "Blackened Soul",
        "Blackest Animus",
        "Rajang Club",
        "Banned Rajang Club",
        "Cursed Rajang Club",
        "Bright Night",
        "Sainted Dame",
        "Gartered Rood",
        "Red Divine Flame",
        "Red Demonic Flame",
        "Red Efreet's Flame",
        "Bloodslaughter",
        "Cold Blood",
        "Mortal Heart",
        "Odyssey Blade+",
        "Master Odyssey",
        "Chalcamine Sword",
        "Chalcomatia",
        "Melynx Tool",
        "Plesiperse Spike",
        "Plesiperse Spike+",
        "Eternal Vengeance",
        "Daora's Maelstrom",
        "Eldaora's Sturm",
        "Divine Insodus",
        "Divine Egression",
        "Teostra's Spada",
        "Teostra's Emblem",
        "Kirin Bolt Maximus",
        "Icemaster Kirin",
        "Ukanlos Soul Hatchet",
        "Ukanlos Skyhatchet",
        "Orochi",
        "Yaegaki",
        "Vaca the Mazelord",
        "Dalamadur Hatchet",
        "Bescaled Dalamadur",
        "True Fatalis Sword",
        "True Ruiner Sword",
        "W. Fatalis Sword",
        "Naab Sword",
        "Naab Sword+",
        "Seditious Fang",
        "Panja Sedition",
        "Valorous Soldier",
        "Kyrie Ruin",
        "Black Belt Sword",
        "Master Sword G",
        "dummy231",
        "Star Knight Sword",
        "dummy233",
        "Ms. M.H. Puppet",
        "Saint Luxseed",
        "Demon Valkcreed",
        "Poison Battleaxe (red)",
        "Poison Battleaxe (yellow)",
        "Poison Battleaxe (green)",
        "Poison Battleaxe (blue)",
        "Poison Battleaxe (purple)",
        "Giltanas Epee (red)",
        "Giltanas Epee (yellow)",
        "Giltanas Epee (green)",
        "Giltanas Epee (blue)",
        "Giltanas Epee (purple)"
    }; const wxArrayString wxSNS_LIST(247, SNS_LIST);

    const char *HAMMER_LIST[] = {
        "(None)",
        "War Hammer",
        "War Hammer+",
        "War Mace",
        "Iron Striker",
        "Iron Striker+",
        "Iron Impact",
        "Kurogane",
        "Iron Devil",
        "Fist of Fury",
        "Frozen Core",
        "Cocytus",
        "Gun Hammer",
        "Deadeye Revolver",
        "Sanctioned Gunhammer",
        "Burning Crusher",
        "Purse Bop",
        "Purse Bop+",
        "Bleeding Bopper",
        "Bleeding Basher",
        "Cluster Hammer",
        "Cluster Hammer+",
        "Cluster Musterer",
        "Master Musterer",
        "Usurper's Thunder",
        "Despot's Crackle",
        "Brimstren Drakemaw",
        "Mane Malice",
        "Mane Malice Rajang",
        "Accelerated Hammer",
        "Boosted Hammer",
        "Nitro Boost Hammer",
        "Full Throttle Mace",
        "Overclocker",
        "Wuchtblick",
        "Grimmblick",
        "Ächtungsblick",
        "Le Jugement",
        "Bone Hammer",
        "Bone Hammer+",
        "Bone Bludgeon",
        "Bone Bludgeon+",
        "Heavy Bone Bludgeon",
        "Striped Striker",
        "Tigrex Hammer",
        "Accursed Striker",
        "Tussive Gravemace",
        "Gigaton Hammer",
        "Titan Hammer",
        "Graviton Hammer",
        "Venom Crater",
        "Meaty Smash",
        "Meaty Smash+",
        "Meaty Press",
        "Pressure Cooker",
        "Venom Monster",
        "Venom Monster+",
        "Death Venom Hammer",
        "Purple Mace",
        "Pitohui Bird Mace",
        "Red Bludgeon",
        "Huracan Hammer",
        "Leonid Starcrusher",
        "Huracan Blueblaze",
        "Dios Tailhammer",
        "Dios Tailhammer+",
        "Demolition Hammer",
        "Kut-Ku Pick",
        "Kut-Ku Pick+",
        "Kut-Ku Thwap",
        "Dynamic Hammer",
        "Violence Hammer",
        "Raven Torrent",
        "Wolf Torrent",
        "Crow Torrent",
        "Basarios Blow",
        "Basarios Bash",
        "Oregalore",
        "Gemgalore",
        "Harmingbird",
        "Toxikeet",
        "Potio Bocciolo",
        "Carapace Hammer",
        "Carapace Hammer+",
        "Barroth Hammer",
        "Binding Bludgeon",
        "Armored Gogue",
        "Gaiasp",
        "Great Gaiarch",
        "White Kitty Stamp",
        "White Kitty Hammer",
        "Black Kitty Stamp",
        "Black Kitty Hammer",
        "Rusted Hammer",
        "Tarnished Hammer",
        "Breath Core Hammer",
        "Lava Core Hammer",
        "Teo Cratermaker",
        "Teo Cratergouger",
        "Worn Hammer",
        "Weathered Hammer",
        "Pulsating Core",
        "Icesteel Hammer",
        "Daora's Colossus",
        "Eminence",
        "Kushinada",
        "Devil's Due",
        "Devil's Crush",
        "Consummate Hammer",
        "Helixbone Slab",
        "The Extricating Blow",
        "Fatalis Buster",
        "dummy112",
        "dummy113",
        "dummy114",
        "dummy115",
        "Hidden Breaker (red)",
        "Hidden Breaker (yellow)",
        "Hidden Breaker (green)",
        "Hidden Breaker (blue)",
        "Hidden Breaker (purple)",
        "Leonid Starcrusher (red)",
        "Leonid Starcrusher (yellow)",
        "Leonid Starcrusher (green)",
        "Leonid Starcrusher (blue)",
        "Leonid Starcrusher (purple)",
        "Lunastra's Crown (red)",
        "Lunastra's Crown (yellow)",
        "Lunastra's Crown (green)",
        "Lunastra's Crown (blue)",
        "Lunastra's Crown (purple)",
        "Devil Masher (red)",
        "Devil Masher (yellow)",
        "Devil Masher (green)",
        "Devil Masher (blue)",
        "Devil Masher (purple)",
        "War Basher (red)",
        "War Basher (yellow)",
        "War Basher (green)",
        "War Basher (blue)",
        "War Basher (purple)",
        "Kitty Hammer (red)",
        "Kitty Hammer (yellow)",
        "Kitty Hammer (green)",
        "Kitty Hammer (blue)",
        "Kitty Hammer (purple)",
        "Ancient Blow",
        "Foolhardy Stone Fist",
        "Cocytus+",
        "Pykrete Punisher",
        "Improved Gunhammer",
        "Imperial Gunhammer",
        "Bleeding Basher+",
        "Bleeding Bludgeon",
        "Master Musterer+",
        "Scylla Maelstrom",
        "Scylla Maeltasrophe",
        "Oppressor's Sway",
        "Orcus Adflictus",
        "Brimstren Drakemaw+",
        "Stygian Industria",
        "Mane Master Rajang",
        "Demonlord Hammer",
        "Logicbreaker",
        "Boulverizer",
        "La Naissance",
        "La Terre",
        "Vergehen/Naissance",
        "Ceanataur Head Axe",
        "Carmine Axe",
        "The Great Divider",
        "Tussive Gravemace+",
        "Wracking Grismace",
        "Venom Crater+",
        "Glasya-Labolas",
        "Pressure Cooker+",
        "Morphing Brinicle",
        "Puffer Smash",
        "Pufferpounder",
        "Gypcer Rammer",
        "Gypceros Ramplifi",
        "Leonid Starcrusher+",
        "Svarog Starsmasher",
        "Rathalos Blueblazon",
        "Novagio Demolisher",
        "Lightbreak Hammer",
        "Mysterious Jaw",
        "Pox Torrent",
        "Garuga Effusion",
        "Gemgalore+",
        "Meteorgalore",
        "Bel Fiore",
        "Fiore Fantastico",
        "Barroth Basher",
        "Barroth Grandbasher",
        "Armored Gigagogue",
        "Mother Gaiarch",
        "Gaia Horizon",
        "Gold Cat Hammer",
        "Gold Cat Crusher",
        "Crust Core Hammer",
        "Teostra del Torre",
        "Meteoric Core",
        "Daora's Hyperborea",
        "Eldaora's Colossus",
        "Genie's Expanse",
        "Fugaku",
        "Nadeshiko",
        "Doomhammer Blood""",
        "Ukanlos Trampler",
        "Ukanlos Skysmasher",
        "Edward the Tremor",
        "Dalamadur Hammer",
        "Agonized Dalamadur",
        "Fatalis Demolisher",
        "Fatalis Iregard",
        "Fatalis Ruiner",
        "Matraca Hammer",
        "Matraca Hammer+",
        "Seditious Hammer",
        "Qadar Sedition",
        "Empty Cage",
        "Desmos Admonition",
        "Arluq Whammer",
        "Swinging Scarluq",
        "Pride of Harth",
        "Black Belt Hammer",
        "Portsmark",
        "Teddybear",
        "Enormous Ham",
        "Ham of Hams",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "Apocalypse's Herald",
        "H.O.S.",
        "Crystal Nova (red)",
        "Crystal Nova (yellow)",
        "Crystal Nova (green)",
        "Crystal Nova (blue)",
        "Crystal Nova (purple)",
        "Dragonbreaker (red)",
        "Dragonbreaker (yellow)",
        "Dragonbreaker (green)",
        "Dragonbreaker (blue)",
        "Dragonbreaker (purple)"
    }; const wxArrayString wxHAMMER_LIST(247, HAMMER_LIST);

    const char *LANCE_LIST[] = {
        "(None)",
        "Iron Lance",
        "Iron Lance+",
        "Knight Lance",
        "Knight Lance+",
        "Rampart",
        "Rampart+",
        "Babel Spear",
        "Elder Babel Spear",
        "Drill Lance",
        "Megadrill Lance",
        "Eiferschild",
        "Fieberschild",
        "Zornesschild",
        "L'Égide",
        "Venom Lance",
        "Basarios Venom Spear",
        "Gravios Spear",
        "Black Gravios Spear",
        "Diablos Lance",
        "Diablos Spear",
        "Fragrance",
        "Fragrance+",
        "Dark Spear",
        "Darkness",
        "Bone Lance",
        "Bone Lance+",
        "Spiked Spear",
        "Spiked Spear+",
        "Spiked Javelin",
        "Tiger Stinger",
        "Tigrex Lance",
        "Accursed Stinger",
        "Predator Gravelance",
        "Dios Stinger",
        "Dios Stinger+",
        "Demolition Lance",
        "Red Tail",
        "Spear of Prominence",
        "Silver Prominence",
        "Blue Prominence",
        "Twistcrawl",
        "Twistcrawl+",
        "Twisting Crawler",
        "Paratwist Crawler",
        "Expelger",
        "Expelgorer",
        "Expelgorer+",
        "Expelgouger",
        "Rexpelgouger",
        "Gobulu Muruka",
        "Gobuluku Muraaka",
        "Usurper's Coming",
        "Despot's Cacophony",
        "Demon Lance",
        "Great Demon Lance",
        "Brimstren Draketail",
        "Carnivicious",
        "Carnivicious+",
        "Omnivicious",
        "Omnivoracious",
        "Incessant Raven",
        "Incessant Wolf",
        "Incessant Crow",
        "Blue Crater",
        "Doom Crown",
        "Sharq Byte",
        "Sharq Attaq",
        "Aqua Spear",
        "Stream Spear",
        "Emerald Spear",
        "Watery Trishula",
        "Rusted Lance",
        "Tarnished Lance",
        "Undertaker",
        "High Undertaker",
        "Icesteel Spear",
        "Daora's Fang",
        "Worn Spear",
        "Weathered Spear",
        "Skyscraper",
        "Teostra's Howl",
        "Teostra's Roar",
        "Thunderspear",
        "Thunderlance",
        "Grief Lance",
        "Fiendish Tower",
        "Shellslab Prong",
        "The Steadfast Aegis",
        "Fatalis Lance",
        "Ruiner Lance",
        "dummy91",
        "dummy92",
        "Babel Spear (red)",
        "Babel Spear (yellow)",
        "Babel Spear (green)",
        "Babel Spear (blue)",
        "Babel Spear (purple)",
        "Tusk Lance (red)",
        "Tusk Lance (yellow)",
        "Tusk Lance (green)",
        "Tusk Lance (blue)",
        "Tusk Lance (purple)",
        "Dragonrider Lance (red)",
        "Dragonrider Lance (yellow)",
        "Dragonrider Lance (green)",
        "Dragonrider Lance (blue)",
        "Dragonrider Lance (purple)",
        "Frontrider Lance (red)",
        "Frontrider Lance (yellow)",
        "Frontrider Lance (green)",
        "Frontrider Lance (blue)",
        "Frontrider Lance (purple)",
        "Silver Prominence (red)",
        "Silver Prominence (yellow)",
        "Silver Prominence (green)",
        "Silver Prominence (blue)",
        "Silver Prominence (purple)",
        "Elder Babel Spear+",
        "Lost Babel",
        "Megadrill Lance+",
        "Gigadrill Lance",
        "Le Sage",
        "Le Paladin",
        "Luzifer/Sage",
        "Gravios Lance",
        "Gravios Fire Lance",
        "Cera Creos",
        "Black Tempest",
        "Rising Tempest",
        "Crimson Lance",
        "Crimson Lance+",
        "Crimson War Pike",
        "Crimson Monoblos",
        "Ceramic Blos Lance",
        "White Catastrophe",
        "Darkness+",
        "Dark Din",
        "Predator Gravelance+",
        "Ruthless Grislance",
        "Albrach Demolisher",
        "Lightbreak Lance",
        "Sol Prominence",
        "Immaculate Soul",
        "Soul of Prominence",
        "Paragyred Spear",
        "Asclepius",
        "Jingana",
        "Jingana+",
        "Caduceus",
        "Bone Claw Lance",
        "Bone Claw Lance+",
        "Shell Claw Lance",
        "Giant Hermitaur Lance",
        "Shuraba Lance",
        "Shula Shuraba",
        "White Shula Shuraba",
        "Gobulaluku Bosca",
        "Gobulaluku Aquir",
        "Oppressor's Genesis",
        "Orcus Galeus",
        "Brimstren Draketail+",
        "Stygian Ira",
        "Demonlance Rajang",
        "Demonray Rajang",
        "The Destructor",
        "Icelance Zamtrios",
        "Carnelian Lance",
        "Crystalis",
        "Tusk Lance",
        "Sabertooth",
        "Incessant Pox",
        "Garuga Incessance",
        "Eterno Crown",
        "Aidion Crown",
        "Sharq Assawlt",
        "Watery Trishula+",
        "Esmeralda's Tide",
        "Neo Undertaker",
        "Daora's Regulus",
        "Eldaora's Fang",
        "Skyscraper+",
        "Skysunderer",
        "Teostra's Fire",
        "Naar Thunderlance",
        "Nero's Atrocity",
        "Ukanlos Calamity",
        "Ukanlos Skysweeper",
        "Ethelred the Ready",
        "Dalamadur Lance",
        "Generous Dalamadur",
        "True Fatalis Lance",
        "True Ruiner Lance",
        "W. Fatalis Lance",
        "Harbah Lance",
        "Harbah Lance+",
        "Seditious Lance",
        "Hadad Sedition",
        "Fettering Rebuke",
        "Aether Geghard",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "Seven-star lance (red)",
        "Seven-star lance (yellow)",
        "Seven-star lance (green)",
        "Seven-star lance (blue)",
        "Seven-star lance (purple)",
        "Estoc (red)",
        "Estoc (yellow)",
        "Estoc (green)",
        "Estoc (blue)",
        "Estoc (purple)",
        "Hell Phalanx",
        "Purification"
    }; const wxArrayString wxLANCE_LIST(216, LANCE_LIST);

    const char *LBG_LIST[] = {
        "(None)",
        "Cross Bowgun",
        "Cross Bowgun+",
        "Grenade Launcher",
        "Grenade Launcher+",
        "Grenade Revolver",
        "Rathling Gun",
        "Rathling Doombringer",
        "Rathling Phoenix",
        "Azurathling Skysear",
        "Azurathling Sunsear",
        "Blossomayhem",
        "Jaggid Fire",
        "Bandit Fire",
        "Bandit's Rage",
        "Usurper's Crime",
        "Usurper's Crime+",
        "Despot's Wildfire",
        "Brimstren Drakekiss",
        "Brimstren Drakevow",
        "Cross Blitz",
        "Cross Blitzkrieg",
        "Shotgun (Azure)",
        "Blue Shooter",
        "Simple Shooter",
        "Simple Shooter+",
        "Shotgun (Blood)",
        "Crimson Blade Shower",
        "Rouge Shooter",
        "Shotgun (Green)",
        "Green Blade Shower",
        "Vert Shooter",
        "Shell Shooter",
        "Shell Gatling",
        "Insect Vulcan",
        "Hornet's Nest",
        "Sawgun",
        "Sawgun+",
        "Buzzawgun",
        "Buzzawcannon",
        "Fäulnisschleuder",
        "Wahnschleuder",
        "Teufelsschleuder",
        "La Lumière",
        "Le Condamnateur",
        "Dios Blaster",
        "Dios Blaster+",
        "Demolition Gun",
        "Khezu Syringe",
        "Khezu Hypo",
        "Hyodermic Miracle",
        "Kut-Ku Anger",
        "Kut-Ku Anger+",
        "Kut-Ku Counterattack",
        "Kut-Ku Rage",
        "Kut-Ku Barrage",
        "Raven Do",
        "Wolf Do",
        "Crow Do",
        "Royal Launcher",
        "Royal Torrent",
        "Royal Inundation",
        "Barro Barrel",
        "Barro Barrel+",
        "Barrozooka",
        "Thundacrus",
        "Thundacrus Rex",
        "Blizzard Cannon",
        "Tabula Blizzara",
        "Felyne Helldoll",
        "Black Parasol",
        "Demon's Isle",
        "Demon's Island",
        "God's Isle",
        "God's Island",
        "Blitz Bowgun",
        "Blitz Kirin",
        "Frigid Bowgun",
        "Frigid Kirin",
        "Devil's Grin",
        "Devil's Madness",
        "Diregun Dementia""",
        "Rajang Barrage",
        "Ten Thousand Volts",
        "Barro Barrel (red)",
        "Barro Barrel (yellow)",
        "Barro Barrel (green)",
        "Barro Barrel (blue)",
        "Barro Barrel (purple)",
        "Thundercrack (red)",
        "Thundercrack (yellow)",
        "Thundercrack (green)",
        "Thundercrack (blue)",
        "Thundercrack (purple)",
        "Burst Revolver",
        "Volarevolver",
        "Searulean Firedance",
        "Searulean Firebath",
        "Mille Blossomayhem",
        "Prosperity",
        "Merciless Rage",
        "Oppressor's Rift",
        "Orcus Barqus",
        "Brimstren Drakevow+",
        "Stygian Invidia",
        "Blue Shooter+",
        "Blue Burst",
        "Rouge Shooter+",
        "Rouge Burst",
        "Vert Shooter+",
        "Machine Strafer",
        "Battalion Strafer",
        "Precision Pusca",
        "Precision Punisher",
        "La Vertu",
        "L'Éden",
        "Fäulnis/Vertu",
        "Ballista Demolisher",
        "Ballista Demolisher+",
        "Lightbreak Gun",
        "Blood Syringe",
        "Blood Injection",
        "Kut-Ku Barrage+",
        "Garuga Espringal",
        "Maelstrom",
        "Maelstrom+",
        "Plesioth Drencher",
        "Aurora Flare",
        "Glacialahti",
        "Arctica Cannon",
        "Neo Thundacrus",
        "Eclair Whitebolt",
        "Nether Phloxion",
        "Diamond Frost",
        "Diamond Crest",
        "Felyne Heavendoll",
        "God's Archipelago",
        "Blitz Kirin King",
        "Frigid Kirin King",
        "Doomgun Dementia""",
        "Ten Million Volts",
        "Demonlord Cannon",
        "Tigrex Tank",
        "Tigrex Wargun",
        "Heavy Grisfire",
        "Zhen Angler",
        "Gobul Ganador",
        "Icesteel Wasp",
        "Daora's Hornet",
        "Eldaora's Hornet",
        "Genie's Lamp",
        "Ukanlos Flame Bow",
        "Ukanlos Skylighter",
        "Penetrating Gaze",
        "Hayha Voidmaker",
        "Krasnojarsk the Mad",
        "Dalamadur Fire",
        "Buoyant Dalamadur",
        "Dark Parasol",
        "Dith Valor",
        "Absolute Bowgun",
        "Rasasa Bowgun",
        "Rasasa Bowgun+",
        "Seditious Shot",
        "Vayu Sedition",
        "Bethorned Dystopia",
        "Shakalaka Prized Bow",
        "Hexed Shaka Bow",
        "Kettleblower",
        "Kettleblower Deluxe",
        "Arm Cannon",
        "Frilly Pink Parasol",
        "DUMMY",
        "Frilly Parasol (red)",
        "Frilly Parasol (yellow)",
        "Frilly Parasol (green)",
        "Frilly Parasol (blue)",
        "Frilly Parasol (purple)",
        "Durambarrel (red)",
        "Durambarrel (yellow)",
        "Durambarrel (green)",
        "Durambarrel (blue)",
        "Durambarrel (purple)",
        "Scatterfly Rack",
        "Rebel Paradigm"
    }; const wxArrayString wxLBG_LIST(185, LBG_LIST);

    const char *HBG_LIST[] = {
        "(None)",
        "Bone Shooter",
        "Bone Shooter+",
        "Straw Drumcannon",
        "Shirabeo",
        "Ratatat Drumcannon",
        "Queen's Longfire",
        "Queen's Farflier",
        "Queen's Scionfire",
        "Bone Buster",
        "Bone Blaster",
        "Agnablaster",
        "Agnablazer",
        "Bear Barrel",
        "Arbearalest",
        "Arzuros Gun",
        "Arzuros Gun+",
        "Power Stinger",
        "Power Stinger+",
        "Wild Stinger",
        "Ner Bustergun",
        "Ner Bustergun+",
        "Buster Blaster",
        "Gravios Howl",
        "Gravios Gigahowl",
        "Gravios Roar",
        "Gravios Gigaroar",
        "Mightning",
        "Loyal Thunder",
        "Tigrex Howl",
        "Tigrex Skull",
        "Accursed Roar",
        "Accursed Bellow",
        "Gravecannon",
        "Furious Gravecannon",
        "Pressurized Plaser",
        "Pressurized Plaser+",
        "Pluripotent Plaser",
        "Tropeco Gun",
        "Pecopious Gun",
        "Bite Blaster",
        "Biting Blast",
        "Dual Threat",
        "Diablazooka",
        "Peerless",
        "Masterless",
        "Arahabaki",
        "Daora's Delphinidae",
        "Daora Grande",
        "Teostra's Artillery",
        "Teostra's Flames",
        "Lunastra's Cannon",
        "Lunastra's Flames",
        "Akantor Cannon",
        "Caudalbone Crook",
        "The Omnipotent Blast",
        "Chaos Wing",
        "Albadash",
        "Vor Cannon",
        "Vor Buster",
        "Dual Threat (red)",
        "Dual Threat (yellow)",
        "Dual Threat (green)",
        "Dual Threat (blue)",
        "Dual Threat (purple)",
        "Chaos Wing (red)",
        "Chaos Wing (yellow)",
        "Chaos Wing (green)",
        "Chaos Wing (blue)",
        "Chaos Wing (purple)",
        "Tetsu Pyrotechnus",
        "Tetsu Pyropinnacle",
        "Empress's Blossom",
        "Empress's Flower",
        "Empress's Doublefleur",
        "Bone Blaster+",
        "Cartilage Blaster",
        "Crab Buster",
        "Heavy Crab Buster",
        "Violet Punisher",
        "Agna Magnum",
        "Agna Scorpion",
        "Arzuros Ozeki",
        "Arzuros Yokozuna",
        "Tödlicher Abzug",
        "Le Désastre",
        "La Foi",
        "Le Déluge",
        "Verrat/Foi",
        "Burst Stinker",
        "Fatal Stinker",
        "Buster Blaster+",
        "Nightfall Blaster",
        "Vampyr Blaster",
        "Gravios Gigacannon",
        "Oppressor's Wedge",
        "Orcus Quarcus",
        "Brimstren Drakemouth",
        "Stygian Humilitas",
        "Accursed Bellow+",
        "Furious Gravecannon+",
        "Livid Griscannon",
        "Dios Cannon",
        "Dios Cannon+",
        "Demolition Cannon",
        "Haize Demolisher",
        "Lightbreak Cannon",
        "Verdant Washbuckler",
        "Captain Verde",
        "Pecopious Thunder",
        "Precision Pico Peco",
        "Ravager Blast",
        "Yellow Buster",
        "Azure Blast",
        "Azure Buster",
        "Nero's Blazooka",
        "Griffon Blazooka",
        "Monodevilcaster",
        "Monodevilcaster+",
        "Monodevilblaster",
        "Utsurowazaru",
        "Eigoh",
        "Daora's Ceti",
        "Eldaora's Delphinidae",
        "Teostra's Firestorm",
        "Lunastra's Firestorm",
        "Kamaeleon",
        "Akantor Skysounder",
        "Ukanlos Cannon",
        "Ukanlos Skyblaster",
        "Robert the Vortex",
        "Dalamadur Cannon",
        "Militant Dalamadur",
        "Altheos Aetheria",
        "Vor Blaster",
        "Destiny's Arm",
        "Fatalis Enslaver",
        "Sayyad Cannon",
        "Sayyad Cannon+",
        "Seditious Cannon",
        "Furia Sedition",
        "Trembling Lordship",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "Gigant Launcher (red)",
        "Gigant Launcher (yellow)",
        "Gigant Launcher (green)",
        "Gigant Launcher (blue)",
        "Gigant Launcher (purple)",
        "Cahoe (red)",
        "Cahoe (yellow)",
        "Cahoe (green)",
        "Cahoe (blue)",
        "Cahoe (purple)",
        "Giant Pan",
        "Romea Crossbow"
    }; const wxArrayString wxHBG_LIST(157, HBG_LIST);

    const char *LS_LIST[] = {
        "(None)",
        "Iron Katana",
        "Iron Grace",
        "Iron Gospel",
        "Eager Cleaver",
        "Devil Slicer",
        "Wailing Ghost",
        "Grand Wailing Ghost",
        "Stahlfakt",
        "Stahlrecht",
        "Stahlurteil",
        "La Justicière",
        "Ice Blade",
        "Ice Blade+",
        "Edel's Snowflake",
        "Edel's Ice",
        "Aikuchi",
        "Unbranded Aikuchi",
        "Lieutenant's Aikuchi",
        "Toad Abetter",
        "Accomplished Abetter",
        "Guardian Sword",
        "Imperial Sword",
        "Wyvern Blade Fall""",
        "Wyvern Blade Blood""",
        "Wyvern Blade Maple""",
        "Wyvern Blade Pale""",
        "Wyvern Blade Blaze""",
        "Dios Katana",
        "Dios Katana+",
        "Demolition Katana",
        "Bone",
        "Large Bone",
        "Canine Katana",
        "Lupine Katana",
        "Cerberus Katana",
        "Tigrine Edge",
        "Tigrine Need",
        "Tigrine Hunger",
        "Tigrine Appetence",
        "Usurper's Boltslicer",
        "Usurper Boltslicer+",
        "Despot's Boltbreaker",
        "Brimstren Drakebone",
        "Coiled Nail",
        "Coiled Nail+",
        "Coiled Saber",
        "Paracoiled Saber",
        "Curviscera",
        "Incurviscera",
        "Incurviscera+",
        "Bicurviscera",
        "Vilcurviscera",
        "Daito Crow",
        "Daito Wolf",
        "Daito Bane",
        "Demon Halberd",
        "Great Demon Halberd",
        "Blood Cry",
        "Blood Cry+",
        "Noble Blood Cry",
        "Bioptimus",
        "Windeater",
        "Notos",
        "Barbarian Blade",
        "Barbarian Sharq""",
        "Hairtail's Hairblade",
        "Hairtail Hairblade+",
        "Fresh Hairblade",
        "Worn Long Sword",
        "Weathered Long Sword",
        "Oblivvion",
        "Icesteel Blade",
        "Daora's Raid",
        "Arbiter",
        "Susano-o",
        "Reaver Cruelty""",
        "Reaver Calamity""",
        "Consummate Katana",
        "Akantor Katana",
        "Tailblade Parallel",
        "The Righteous Swath",
        "Fatalis Sickle",
        "Starlight Gate",
        "Eternal Gate",
        "Wing of Judgment",
        "dummy86",
        "dummy87",
        "dummy88",
        "dummy89",
        "dummy90",
        "EX Arbiter",
        "EX Susano-o",
        "Arbiter (red)",
        "Arbiter (yellow)",
        "Arbiter (green)",
        "Arbiter (blue)",
        "Arbiter (purple)",
        "Saber (red)",
        "Saber (yellow)",
        "Saber (green)",
        "Saber (blue)",
        "Saber (purple)",
        "Rusty Claymore (red)",
        "Rusty Claymore (yellow)",
        "Rusty Claymore (green)",
        "Rusty Claymore (blue)",
        "Rusty Claymore (purple)",
        "Rimeblade (red)",
        "Rimeblade (yellow)",
        "Rimeblade (green)",
        "Rimeblade (blue)",
        "Rimeblade (purple)",
        "Wyvern Blade (red)",
        "Wyvern Blade (yellow)",
        "Wyvern Blade (green)",
        "Wyvern Blade (blue)",
        "Wyvern Blade (purple)",
        "Wrathful Beheader",
        "Rightful Beheader",
        "La Loi",
        "Le Décalogue",
        "Chaos/Loi",
        "Crab Cutter",
        "Daimyo Cutter",
        "Daimyo Cutter+",
        "Hermitaur Slicer",
        "Crimson Scythe",
        "Crimson Scythe+",
        "Monoblos Scythe",
        "White Mantis",
        "Weiss Crescent",
        "Yuki Ichimonji",
        "Silver Ichimonji",
        "Hidden Saber",
        "Hidden Saber+",
        "Deepest Night",
        "Megrez's Asterism",
        "Rampage Edge",
        "Rampage Ironsong",
        "Aqua Guardian",
        "Atlantica",
        "Wyvern Blade Silver""",
        "Wyvern Blade Bloom""",
        "Wyvern Blade Rose""",
        "Wyvern Blade Awe""",
        "Pyro Demolisher",
        "Lightbreak Edge",
        "Tigrine Appetence+",
        "Tigrine Esurience",
        "Oppressor's Law",
        "Orcus Nitorus",
        "Stygian Gula",
        "Charonian Gula",
        "Paracoiled Edge",
        "Parazagged Edge",
        "Hyddra",
        "Hyddra+",
        "Alphard",
        "Vilcurviscera+",
        "Tamopaha",
        "Tamo Saggrama",
        "Daito Pox",
        "Garuga Daito",
        "Evil Demon Halberd",
        "Demonlord Halberd",
        "Bioptimus+",
        "Gloom",
        "Dark Matter",
        "Notos+",
        "Euros",
        "Kibamaru",
        "Premium Hairblade",
        "Oblivvion+",
        "Memento",
        "Daora's Storm",
        "Eldaora's Raid",
        "Imperial Saber",
        "Imperial Shimmer",
        "Phantom Mirage",
        "Nenekirimaru",
        "Onamuchi",
        "Doomblade Slave""",
        "Akantor Strongsword",
        "Ukanlos Slicer",
        "Ukanlos Skydicer",
        "Barwell the Swift",
        "Dalamadur Edge",
        "Clouded Dalamadur",
        "Fatalis Zaggespanon",
        "Fatalis Fotia",
        "Fatalis Ascencia",
        "Dragonwood Blade",
        "Dragonwood Godblade",
        "Dragonwood Cutblade",
        "Khanga Edge",
        "Khanga Edge+",
        "Seditious Edge",
        "Zealous Sedition",
        "Grim Genuflector",
        "Headsman's Requite",
        "Thunderclap",
        "Thunderclap+",
        "Chainslaughter",
        "Centenarian Dagger",
        "Susano Blade",
        "Fan Club Bamboo Rod",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "Crimson Dancer",
        "Nirvana Blade",
        "Netherblade (red)",
        "Netherblade (yellow)",
        "Netherblade (green)",
        "Netherblade (blue)",
        "Netherblade (purple)",
        "Divine Slasher (red)",
        "Divine Slasher (yellow)",
        "Divine Slasher (green)",
        "Divine Slasher (blue)",
        "Divine Slasher (purple)"
    }; const wxArrayString wxLS_LIST(227, LS_LIST);

    const char *SA_LIST[] = {
        "(None)",
        "Bone Axe",
        "Bone Axe+",
        "Bone Smasher",
        "Power Gasher",
        "Massive Gasher",
        "Maximal Gasher",
        "Elite Switch Axe",
        "Elite Switch Axe+",
        "Czar Switch Axe",
        "Amber Slash",
        "Galefrost",
        "Rath Flame Splitter",
        "Rath Blaze Splitter",
        "Rathsplicer",
        "Dragonmaiden Axe",
        "Dragonmaiden Axe+",
        "Gríðr's Landmaker",
        "Azure Rose",
        "Vavoom Axe",
        "Vavoom Axe+",
        "Vavoom Verdict",
        "Vavoom Vengeance",
        "Vavoom Vindication",
        "Usurper's Downpour",
        "Despot's Cloudburst",
        "Brimstren Drakefang",
        "Volt Axe",
        "Notched Doom",
        "Notched Doom+",
        "Notched Tyrant",
        "Notched Oppressor",
        "Dios Axe",
        "Dios Axe+",
        "Demolition Axe",
        "Barbarian Axe",
        "Bold Barbarian Axe",
        "Barbarian Outcast",
        "Pecospander",
        "Pecospander+",
        "Qurupexspander",
        "Wild Axe",
        "Wild Axe+",
        "Ground Dasher",
        "Rex Slasher",
        "Rex Gnasher",
        "Accursed Switcher",
        "Sheltered Graveaxe",
        "Eisenleib",
        "Eisengeist",
        "Eisenherz",
        "La Guillotine",
        "Assault Axe",
        "Blitzkrieg",
        "Binding Roller",
        "Vermilingua",
        "Flickaxe",
        "Flickaxe+",
        "Flicker Axe",
        "Paraflick Axe",
        "Great Inceadeus",
        "Rough Edge",
        "Soulbreaker",
        "Grim Cat",
        "Grimmig Katze",
        "Worn Switch Axe",
        "Weathered Switch Axe",
        "Mundus Altus",
        "Rupture",
        "Izanagi",
        "Peal",
        "Kirin Thunderpeal",
        "Kirin Thunderbolt",
        "Tyrannos",
        "Terror Tyrannos",
        "Saligia Vileaxe",
        "Akantor Switch Axe",
        "Keenscale Phalanx",
        "The Exuberant Bite",
        "Fatalis's End",
        "Ruiner's Bane",
        "dummy81",
        "dummy82",
        "dummy83",
        "dummy84",
        "EX Rupture",
        "EX Izanagi",
        "Mighty Switch Axe (red)",
        "Mighty Switch Axe (yellow)",
        "Mighty Switch Axe (green)",
        "Mighty Switch Axe (blue)",
        "Mighty Switch Axe (purple)",
        "Rough Edge (red)",
        "Rough Edge (yellow)",
        "Rough Edge (green)",
        "Rough Edge (blue)",
        "Rough Edge (purple)",
        "Switch Axe Regnant (red)",
        "Switch Axe Regnant (yellow)",
        "Switch Axe Regnant (green)",
        "Switch Axe Regnant (blue)",
        "Switch Axe Regnant (purple)",
        "Hidden Axe (red)",
        "Hidden Axe (yellow)",
        "Hidden Axe (green)",
        "Hidden Axe (blue)",
        "Hidden Axe (purple)",
        "Dragonmaiden Axe (red)",
        "Dragonmaiden Axe (yellow)",
        "Dragonmaiden Axe (green)",
        "Dragonmaiden Axe (blue)",
        "Dragonmaiden Axe (purple)",
        "General's Strongaxe",
        "Conqueress",
        "Galefrost+",
        "Giga Galefrost",
        "Rathlagration",
        "Rathscension",
        "Azure Rosebloom",
        "Azure Straybloom",
        "Vavoom Nakha",
        "Weird Wacha Nakha",
        "Tanka Talon",
        "Tatanka Talon",
        "Brimstren Drakefang+",
        "Stygian Vanagloria",
        "Remiel Whitebolt",
        "Nether Excellion",
        "Notched Oppressor+",
        "Notched Diavolo",
        "Allagi Tigermaw",
        "Zamtreacherous Maw",
        "Brisant Demolisher",
        "Lightbreak Axe",
        "Bruiser Axe",
        "Chief Bruiser Axe",
        "Waxglare Wand",
        "Qurupexspander+",
        "Helstrong Firebath",
        "Sheltered Graveaxe+",
        "Crazed Grisaxe",
        "Axe Semper Tyrannis",
        "Axe of Gaia",
        "Axe of Thanatos",
        "Axe of Hades",
        "Le Sursis",
        "La Conclusion",
        "Frevel/Sursis",
        "Vermilion Bloodaxe",
        "Paracrux Axe",
        "Basilisk",
        "Cryoseism",
        "Illuyanka",
        "Ceadeed Axe",
        "Soulcrusher",
        "Helios Crusher",
        "Mundus Altus+",
        "Mundus Regius",
        "Teostra's Arx",
        "Teostra's Castle",
        "Daora's Farasa",
        "Daora's Janah",
        "Eldaora's Farasa",
        "Futara",
        "Yamatsumi",
        "Kirin Thunderpeal+",
        "Archbeast Kirin",
        "Bitterbeast Kirin",
        "Doomaxe Downpour""",
        "Akantor Divider",
        "Oda the Conqueror",
        "Dalamadur Axe",
        "Praying Dalamadur",
        "True Fatalis's End",
        "True Ruiner's Bane",
        "Fatalis Force",
        "Aksa Switch",
        "Aksa Switch+",
        "Seditious Axe",
        "Baraq Sedition",
        "Punishable Sin",
        "Wicked Conqueror",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "Shah Bloodseeker",
        "Olvid of the Abyss",
        "Deluge (red)",
        "Deluge (yellow)",
        "Deluge (green)",
        "Deluge (blue)",
        "Deluge (purple)",
        "Motor Burst (red)",
        "Motor Burst (yellow)",
        "Motor Burst (green)",
        "Motor Burst (blue)",
        "Motor Burst (purple)"
    }; const wxArrayString wxSA_LIST(198, SA_LIST);

    const char *GL_LIST[] = {
        "(None)",
        "Iron Gunlance",
        "Iron Gunlance+",
        "Steel Gunlance",
        "Striker's Gunlance",
        "Defender's Gunlance",
        "Imperial Guardlance",
        "General's Arbalance",
        "Admiral's Arbalance",
        "Ancient Gyrelance",
        "Ancient Gyresmite",
        "Red Rook",
        "Red Rook+",
        "Crimson Rook",
        "Silver Rook",
        "Chariot Gun",
        "Dios Gunlance",
        "Dios Gunlance+",
        "Demolition Gunlance",
        "Full Voltage",
        "Full Generator",
        "Red Generator",
        "Bloodied Dynamo",
        "Red Devil Gunlance",
        "Red Devil Smasher",
        "Blue Devil Uberlance",
        "Blue Devil Opus",
        "White Gunlance",
        "White Cannon",
        "Black Gunlance",
        "Seadiver",
        "Seadiver+",
        "Deepbuster",
        "Deep Gunbuster",
        "Bone Gunlance",
        "Great Bone Gunlance",
        "Jaggid Gunlance",
        "Jaggid Gunlance+",
        "Hurricane Gunlance",
        "Tiger Blast",
        "Tigrex Gunlance",
        "Accursed Blast",
        "Menacing Gravegun",
        "Demon Gunlance",
        "Great Demon Gunlance",
        "Tyrannenarm",
        "Verräterarm",
        "Hochmutsarm",
        "L'Onde",
        "Princess Panoply",
        "Princess Panoply+",
        "Ortlinde",
        "Queen's Panoply",
        "Usurper's Roar",
        "Usurper's Roar+",
        "Despot's Phlogiston",
        "Brimstren Drakeblood",
        "Average Hitter",
        "Grand Slam",
        "Hard Hitter",
        "Big Slugger",
        "Lagomberator",
        "Lagomberatrix",
        "Lagomberastrophe",
        "Lagombergeddon",
        "Shell Gunbird",
        "Shell Gunbird+",
        "Noble Gunbird",
        "Royal Gunbird",
        "Peco Teepee",
        "Peco Teepee+",
        "Feather Gunlance",
        "Hypno Cannon",
        "Felyoshka",
        "Felyoshka+",
        "Felicitous Felyoshka",
        "Marine Fisher",
        "Abyssal Fisher",
        "Deep Blue Sea",
        "Leviathan Gunlance",
        "Worn Gunlance",
        "Weathered Gunlance",
        "Obelisk",
        "Luna's Howl",
        "Luna's Flare",
        "Icesteel Gunlance",
        "Daora's Brigia",
        "Brilliance",
        "Amaterasu",
        "Ravenous Gunlance",
        "Insatiable Gunlance",
        "Consummate Gunlance",
        "Akantor Gunlance",
        "Illstarred Gunlance",
        "The Celestial Fall",
        "Fatalis Gunlance",
        "dummy96",
        "dummy97",
        "dummy98",
        "dummy99",
        "Princess Panoply (red)",
        "Princess Panoply (yellow)",
        "Princess Panoply (green)",
        "Princess Panoply (blue)",
        "Princess Panoply (purple)",
        "Full Voltage (red)",
        "Full Voltage (yellow)",
        "Full Voltage (green)",
        "Full Voltage (blue)",
        "Full Voltage (purple)",
        "Luna's Howl (red)",
        "Luna's Howl (yellow)",
        "Luna's Howl (green)",
        "Luna's Howl (blue)",
        "Luna's Howl (purple)",
        "General's Arbalance (red)",
        "General's Arbalance (yellow)",
        "General's Arbalance (green)",
        "General's Arbalance (blue)",
        "General's Arbalance (purple)",
        "Silver Rook (red)",
        "Silver Rook (yellow)",
        "Silver Rook (green)",
        "Silver Rook (blue)",
        "Silver Rook (purple)",
        "Admiral's Arbalance+",
        "Imperial Swornlance",
        "Progenesis",
        "Empire",
        "Lagia Burst",
        "Eutaxy Whitebolt",
        "Nether Jugulus",
        "World's Demise",
        "Eine Wahrheit",
        "Zvolta Demolisher",
        "Lightbreak Gunlance",
        "Blood Bolt",
        "Blood Thunder",
        "Rampage Cannonlance",
        "Rampage Firebelcher",
        "Black Gore Cannon",
        "Black Gore Buster",
        "Megalo Mincer",
        "Jones's Locker",
        "Tetrozonata",
        "Velenofragola",
        "Scissor Gunlance",
        "Scissor Cannon",
        "Violet Cannon",
        "Violet Buster",
        "Monsieur Gore",
        "Monsieur Gore+",
        "Madame Butcher",
        "Seltas Fortitude",
        "Menacing Gravegun+",
        "Hounding Grisgun",
        "Grt Demon Gunlance+",
        "Demonlord Gunlance",
        "Le Mur",
        "La Forteresse",
        "Mauer/Guerre",
        "Shining Ishtar",
        "Shining Astarte",
        "Shimmering Tiamat",
        "Oppressor's Skyfall",
        "Brimstren Drakeblood+",
        "Stygian Avaritia",
        "Big Slugger+",
        "Triple Crown",
        "Lagombalanche",
        "Lagombavalanga",
        "Royal Gunbird+",
        "Nightfall Cannon",
        "Nux Cannon",
        "Hypnos",
        "Cornpopper",
        "Mighty Cornpopper",
        "Diviathan Gunlance",
        "Sea Abyss",
        "Deus Obelisk",
        "Luna's Flare+",
        "Luna's Sun",
        "Daora's Tempest",
        "Eldaora's Brigia",
        "Venomous Perfume",
        "Iwato",
        "Amatsuhiko",
        "Doomlance Greed""",
        "Akantor Cannonlance",
        "Ukanlos Gunlance",
        "Ukanlos Cannonlance",
        "Ethelbald the Dire",
        "Dalamadur Gunlance",
        "Unchained Dalamadur",
        "True Fatalis Gunlance",
        "Hellruin Gunlance",
        "W. Fatalis Gunlance",
        "Jaya Gunlance",
        "Jaya Gunlance+",
        "Seditious Gunlance",
        "Tamarod Sedition",
        "Towering Demise",
        "Auguring Prophet",
        "Bamboo Birdsbane",
        "Bamboo Lionsbane",
        "Bamboo Dragonsbane",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "Fangbreaker (red)",
        "Fangbreaker (yellow)",
        "Fangbreaker (green)",
        "Fangbreaker (blue)",
        "Fangbreaker (purple)",
        "Tyrannenarm (red)",
        "Tyrannenarm (yellow)",
        "Tyrannenarm (green)",
        "Tyrannenarm (blue)",
        "Tyrannenarm (purple)",
        "Era Blazer",
        "Gaping Abyss"
    }; const wxArrayString wxGL_LIST(221, GL_LIST);

    const char *BOW_LIST[] = {
        "(None)",
        "Hunter's Bow I",
        "Hunter's Bow II",
        "Hunter's Bow III",
        "Hunter's Stoutbow I",
        "Hunter's Stoutbow II",
        "Hunter's Stoutbow III",
        "Icicle Bow I",
        "Icicle Bow II",
        "Dios Flier",
        "Dios Flier+",
        "Demolition Bow",
        "Queen Blaster I",
        "Queen Blaster II",
        "Heartshot Bow I",
        "Heartshot Bow II",
        "Selene Moonbroken",
        "Prominence Bow I",
        "Prominence Bow II",
        "Prominence Bow III",
        "Hyperion",
        "Blue Alighter I",
        "Blue Alighter II",
        "Ice Cold Alighter",
        "Freezing Alighter",
        "Wild Bow",
        "Wild Power Bow I",
        "Wild Power Bow II",
        "Jungle Bow I",
        "Jungle Bow II",
        "Tigrex Archer",
        "Tigrex Whisker",
        "Accursed Bow",
        "Piercing Gravebow",
        "Khezu Bow I",
        "Khezu Bow II",
        "Khezu Bow III",
        "Bloodcurdler",
        "Distant Thunder I",
        "Distant Thunder II",
        "Despot's Earlybolt",
        "Brimstren Drakegaze",
        "Brimstren Drakeglare",
        "Entbehrung",
        "Verzweiflung",
        "Untergang",
        "Le Ravisseur",
        "Heat Haze",
        "Hulking Haze",
        "Feminine Haze",
        "Formidable Haze",
        "Absolute Deviance",
        "Scylla Fist I",
        "Scylla Fist II",
        "Scylla Weave I",
        "Scylla Weave II",
        "Scylla Shredder",
        "Kut-Ku Stave I",
        "Kut-Ku Stave II",
        "Kut-Ku Stave III",
        "Blue Kut-Ku Stave I",
        "Blue Kut-Ku Stave II",
        "Crow Bow",
        "Wolf Bow",
        "Jinx Bow",
        "Arca Raptora",
        "Amnis",
        "Morsel Bowfish",
        "Ample Bowfish",
        "Kelbi Stingshot",
        "Kelbi Strongshot",
        "Supplication",
        "Tsukuyomi",
        "Beast Thunderbow",
        "Beastking Thunderbow",
        "Prayerful Victoria",
        "Icesteel Bow",
        "Daora's Sagittarii",
        "Bow of Hope & Valor",
        "Akantor Bow",
        "Cradlecrush Embrace",
        "The Keen Stratagem",
        "Bow of Rack & Ruin",
        "dummy83",
        "dummy83",
        "Hero's Bow",
        "Sacred Bow",
        "Akantor Bow (red)",
        "Akantor Bow (yellow)",
        "Akantor Bow (green)",
        "Akantor Bow (blue)",
        "Akantor Bow (purple)",
        "Prominence Bow (red)",
        "Prominence Bow (yellow)",
        "Prominence Bow (green)",
        "Prominence Bow (blue)",
        "Prominence Bow (purple)",
        "Queen Blaster (red)",
        "Queen Blaster (yellow)",
        "Queen Blaster (green)",
        "Queen Blaster (blue)",
        "Queen Blaster (purple)",
        "Icesteel Bow (red)",
        "Icesteel Bow (yellow)",
        "Icesteel Bow (green)",
        "Icesteel Bow (blue)",
        "Icesteel Bow (purple)",
        "Bow of Rack & Ruin (red)",
        "Bow of Rack & Ruin (yellow)",
        "Bow of Rack & Ruin (green)",
        "Bow of Rack & Ruin (blue)",
        "Bow of Rack & Ruin (purple)",
        "Icicle Bow III",
        "Névé Bow",
        "Warflare Demolisher",
        "Lightbreak Bow",
        "Selene Moonbroken+",
        "Artemis Moonmaker",
        "Hyperion+",
        "Uranus Herald",
        "Freezing Alighter+",
        "Hailstorm",
        "Quartzlight",
        "Crystal Lode",
        "Jungle Bow III",
        "Jungle Bow IV",
        "Piercing Gravebow+",
        "Soaring Grisbow",
        "Bloodcurdler+",
        "Splattika",
        "Oppressor's Wing",
        "Orcus Sagittus",
        "Stygian Patientia",
        "Charonian Patientia",
        "Le Désir",
        "L'Innocence",
        "Verzweiflung/Désir",
        "Brazencord",
        "Gigacles",
        "Gigantomachy",
        "Gold Popillia",
        "Golden Ray",
        "Scylla Webdart",
        "Weblivion",
        "Wide Weblivion",
        "Blue Kut-Ku Stave III",
        "Blue Kut-Ku Stave IV",
        "Pox Bow",
        "Garuga Oyumi",
        "Daimyo's Warbow I",
        "Daimyo's Warbow II",
        "Daimyo's Warbow III",
        "Great Purple Emperor I",
        "Great Purple Emperor II",
        "Diablos Coilbender",
        "Cera Cyclord",
        "Fluctus",
        "Viand Bowfish",
        "Kelbi Strongshot+",
        "Great Kelbi Deershot",
        "Amenokago",
        "Tamanoya",
        "Archbeast Thunderbow",
        "Archbeast Paragon",
        "Prayerful Victoria+",
        "Heedful Elizabeth",
        "Daora's Toxotes",
        "Eldaora's Sagittarii",
        "Courageous Wish",
        "Genie's Grimoire",
        "Akantor Chaos Bow",
        "Ukanlos Bow",
        "Ukanlos Skyflier",
        "Yoichi the Sighted",
        "Dalamadur Bow",
        "Enraged Dalamadur",
        "Exterminator Bow II",
        "Red Heaven Ruiner",
        "Victory and Glory",
        "Shalya Bow",
        "Shalya Bow+",
        "Seditious Arrow",
        "Kama Sedition",
        "Unwelcoming Gaol",
        "Calamitous Cupid",
        "Sacred Bow G",
        "Seahorse Harp",
        "Bamboo Taketori",
        "Bamboo Okina",
        "Bamboo Kaguya",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "DUMMY",
        "Eclipse Bow (red)",
        "Eclipse Bow (yellow)",
        "Eclipse Bow (green)",
        "Eclipse Bow (blue)",
        "Eclipse Bow (purple)",
        "Dragon Bow (red)",
        "Dragon Bow (yellow)",
        "Dragon Bow (green)",
        "Dragon Bow (blue)",
        "Dragon Bow (purple)",
        "Moonlit Phoenix",
        "Daybreak Arrow"
    }; const wxArrayString wxBOW_LIST(206, BOW_LIST);

    const char *DB_LIST[] = {
        "(None)",
        "Matched Slicers",
        "Matched Slicers+",
        "Dual Slicers",
        "Dual Hatchets",
        "Dual Hatchets+",
        "Dual Cleavers+",
        "Hurricane",
        "Cyclone",
        "Rex Slicers",
        "Tigrex Claws",
        "Accursed Slicers",
        "Pouncing Graveclaws",
        "Freezing Daggers",
        "Freezing Daggers+",
        "Icicle Daggers",
        "Frozen Death",
        "Insecticutters",
        "Insecticutters+",
        "Insectiscythes",
        "Alated Insect",
        "Sworn Rapiers",
        "Holy Sabers",
        "Guild Knight Sabers",
        "Master Sabers",
        "Jaggid Shotels",
        "Leader's Shotels",
        "Fledderklauen",
        "Hungerklauen",
        "Aasklauen",
        "Les Apôtres",
        "Cleaving Jaws",
        "Cleaving Jaws+",
        "Cool Cleavers",
        "Frozen Cleavers",
        "Bone Scythes",
        "Bone Scythes+",
        "Chief's Scythes",
        "Dual Battleaxe",
        "Dual Battleaxe+",
        "Double Tabarzin",
        "Terminal Toxin",
        "Mortal Miasma",
        "Dual Chameleos",
        "Twin Flames",
        "High Twin Flames",
        "Wyvern Lovers",
        "Wyvern Strife",
        "Pink Maracas",
        "Funky Maracas",
        "Jungle Maracas",
        "Evergreen",
        "Whirlitwists",
        "Whirlitricks",
        "Whirlitorture",
        "Spiral Edges",
        "Gyro Wedges",
        "Snow Slicers",
        "Snow Sisters",
        "Maulagombs",
        "Brawlagombs",
        "Twin Chainsaws",
        "Usurper's Fulgur",
        "Despot's Blitz",
        "Levin Acrus",
        "Brimstren Drakeclaws",
        "Vprey Claws",
        "High Vprey Claws",
        "Raven Tessen",
        "Wolf Tessen",
        "Crow Tessen",
        "Kut-Ku Pair",
        "Kut-Ku Pair+",
        "Melting Wail",
        "Melting Blazer",
        "Dios Slicers",
        "Dios Slicers+",
        "Demolition Blades",
        "Dual Dragon",
        "Dual Dragon Ultimus",
        "Dual Dragon Ultimus+",
        "Felyne and Melynx",
        "Felyne and Melynx+",
        "Plesioth Cutlasses",
        "Plesioth Machetes",
        "Verdant Slashers",
        "Alluvion Slashers",
        "Glutton's Tools",
        "Gorger's Tools",
        "Worn Blades",
        "Weathered Blades",
        "Enduring Schism",
        "Twin Nails",
        "Fire and Ice",
        "Monarch",
        "Kirin Bolts",
        "Ritual Hailscreamers",
        "Wrath & Rancor",
        "Wrathful Predation",
        "Consummate Pair",
        "Akantor Blades",
        "Blackspine Bundles",
        "The Wrackful Gemini",
        "Ebonblood Twindrakes",
        "dummy104",
        "dummy105",
        "dummy106",
        "Dual Kut-Ku",
        "dummy108",
        "dummy109",
        "Twins Regnant (red)",
        "Twins Regnant (yellow)",
        "Twins Regnant (green)",
        "Twins Regnant (blue)",
        "Twins Regnant (purple)",
        "Vprey Claws (red)",
        "Vprey Claws (yellow)",
        "Vprey Claws (green)",
        "Vprey Claws (blue)",
        "Vprey Claws (purple)",
        "Tessen (red)",
        "Tessen (yellow)",
        "Tessen (green)",
        "Tessen (blue)",
        "Tessen (purple)",
        "Ritual Ephemera (red)",
        "Ritual Ephemera (yellow)",
        "Ritual Ephemera (green)",
        "Ritual Ephemera (blue)",
        "Ritual Ephemera (purple)",
        "Guild Knight Sabers (red)",
        "Guild Knight Sabers (yellow)",
        "Guild Knight Sabers (green)",
        "Guild Knight Sabers (blue)",
        "Guild Knight Sabers (purple)",
        "DUMMY",
        "Tornado Hatchets",
        "Typhoon",
        "Pouncing Graveclaws+",
        "Razor Grisclaws",
        "Gelid Mind",
        "Gelid Soul",
        "Alated Insect+",
        "Entomotheos",
        "Master Sabers+",
        "Holy Guild Knight",
        "Le Paradis",
        "Le Shangri-La",
        "Inferno/Paradis",
        "Névé Bite",
        "Blizztrios Fangs",
        "Sandgnashers",
        "Psammophages",
        "Flamestorm",
        "Salamanders",
        "Ignis Noire",
        "Agnaktor Inferno",
        "Chameleos Blades",
        "Wyvern Strife+",
        "Wyvern Conciliation",
        "Evergreen+",
        "Paradise Green",
        "Crossdrills",
        "Crossveldts",
        "Crossenders",
        "Brawlagombs+",
        "Appallagombs",
        "Neo Twin Acrus",
        "Neo Acrus Whitebolt",
        "Brimstren Drakeclaws+",
        "Stygian Superbia",
        "Pox Tessen",
        "Garuga Gunsen",
        "Garuga Lovebirds",
        "Megiddo Rippers",
        "Megiddo Breakers",
        "Spectral Demolisher",
        "Lightbreak Twins",
        "Dual Dragons Angst""",
        "Diablos Bashers",
        "Diablos Sinidex",
        "Sinistrus Dextraos",
        "Felyne and Melynx++",
        "Jade Plesioth Fans",
        "Jade Battlefanzers",
        "Savortooths",
        "Enduring Sacrifice",
        "Enduring Surrender",
        "Blizzard and Blaze",
        "Twin Elders",
        "Wunderkirins",
        "Ritual Eidolons",
        "Suzuka Takamaru",
        "Suzuka Otakemaru",
        "Doomfang Envoys""",
        "Akantor Shadow Claws",
        "Ukanlos Ruinblades",
        "Ukanlos Skyrippers",
        "Mbale the Acute",
        "Dalamadur Spikes",
        "Amber Dalamadur",
        "Twinbane Blades",
        "Twinbane Twilight",
        "Ultimus Apocalypse",
        "Zakun Twins",
        "Zakun Twins+",
        "Seditious Talons",
        "Serre Sedition",
        "Recriminators",
        "Eternal Leavetakers",
        "Shaka Scarecrows",
        "Chum Scarecrows",
        "Chum-Chum Scarecrows",
        "dummy213",
        "Fan Club Fans",
        "DUMMY",
        "DUMMY",
        "Sea-king's Twins (red)",
        "Sea-king's Twins (yellow)",
        "Sea-king's Twins (green)",
        "Sea-king's Twins (blue)",
        "Sea-king's Twins (purple)",
        "Blizzarioths (red)",
        "Blizzarioths (yellow)",
        "Blizzarioths (green)",
        "Blizzarioths (blue)",
        "Blizzarioths (purple)",
        "Crooked Blades",
        "Cross Inferno"
    }; const wxArrayString wxDB_LIST(229, DB_LIST);

    const char *HH_LIST[] = {
        "(None)",
        "Metal Bagpipe",
        "Metal Bagpipe+",
        "Great Bagpipe",
        "Heavy Bagpipe",
        "Heavy Bagpipe+",
        "Fortissimo",
        "Master Bagpipe",
        "Sforzando",
        "Kummerklang",
        "Gramklang",
        "Trauerklang",
        "La Sépulture",
        "Valkyrie Chordmaker",
        "Valkyrie Chordmaker+",
        "Queen's Chordmaker",
        "Gold Chordmaker",
        "Kecha Whappa",
        "Kecha Whappa+",
        "Kechachacha Whappa",
        "Kecha Thumpa",
        "Kecha Clanga",
        "Usurper's Growl",
        "Usurper's Growl+",
        "Despot's Thunderclap",
        "Brimstren Drakesong",
        "Ice Kazoo",
        "Glacial Kazoo",
        "Frost Groaner",
        "Frost General",
        "Bone Horn",
        "Bone Horn+",
        "Hunter's Horn",
        "Hunter's Horn+",
        "Native's Horn",
        "Striped Gong",
        "Tigrex Horn",
        "Accursed Wail",
        "Howling Gravedrum",
        "Dios Bell",
        "Dios Bell+",
        "Demolition Chime",
        "Khezu Horn",
        "Khezu Flute",
        "Blood Horn",
        "Blood Flute",
        "War Drum",
        "War Bongo",
        "War Conga",
        "Jungle Bongo",
        "Jungle Conga",
        "Danger Call",
        "Danger Call+",
        "Hazardous Call",
        "Parahazard Call",
        "Velociprey Balloon",
        "Velociprey Balloon+",
        "Raven Shamisen",
        "Wolf Shamisen",
        "Crow Shamisen",
        "Basarios Rock",
        "Basarios Rock Mk.II",
        "Volcanic Rock",
        "Volcanic Gig",
        "Beating Gunrock",
        "Fleeting Gunrock",
        "Vicello Nulo (W)",
        "Vicello Unu (W)",
        "Vicello Du (W)",
        "Magia Charm",
        "Dragonwood Flute",
        "Worn Horn",
        "Weathered Horn",
        "Avenir's Music Box",
        "Akantor Horn",
        "Veilglare Hymn",
        "The Ascending Strain",
        "Fatalis Menace",
        "dummy78",
        "dummy79",
        "Megaphone",
        "Basarios Rock (red)",
        "Basarios Rock (yellow)",
        "Basarios Rock (green)",
        "Basarios Rock (blue)",
        "Basarios Rock (purple)",
        "Hellstrings (red)",
        "Hellstrings (yellow)",
        "Hellstrings (green)",
        "Hellstrings (blue)",
        "Hellstrings (purple)",
        "Swell Shell (red)",
        "Swell Shell (yellow)",
        "Swell Shell (green)",
        "Swell Shell (blue)",
        "Swell Shell (purple)",
        "Gold Chordmaker (red)",
        "Gold Chordmaker (yellow)",
        "Gold Chordmaker (green)",
        "Gold Chordmaker (blue)",
        "Gold Chordmaker (purple)",
        "Sforzando+",
        "Rinforzato",
        "La Joie",
        "Le Grégorien",
        "Grimm/Joie",
        "Gold Chordmaker+",
        "Lunar Chordmaker",
        "Kecha Clanga+",
        "Kecha Clanvira",
        "Oppressor's Boon",
        "Brimstren Drakesong+",
        "Stygian Tristitia",
        "Denden Daiko",
        "Denden Doomsounder",
        "Poli'ahu Pipe",
        "Phenomenal Phlute",
        "Howling Gravedrum+",
        "Dancing Grisdrum",
        "Timbral Demolisher",
        "Lightbreak Timbre",
        "Shell Castanet",
        "Shell Castanet+",
        "Colored Castanet",
        "Crabby Castanet",
        "Klick-Klack",
        "Blood Flute+",
        "Brute Flute",
        "Jungle Conga+",
        "Primal Conga",
        "Parahazard Call+",
        "Para Calamity",
        "Naja Warning",
        "Naja Alluvion",
        "Pox Shamisen",
        "Garuga Shamisen",
        "Volcanic Gig+",
        "Conflagrig",
        "Heavy Facemelter",
        "Lullaby Facemelter",
        "Magia Charmbell",
        "Aria Rhota",
        "Dragonwood Godflute",
        "Avenir's Music Box+",
        "Eternal Music Box",
        "Teostra's Tiple",
        "Teostra's Orphée",
        "Daora's Taus",
        "Daora's Baphophone",
        "Eldaora's Taus",
        "Genie's Ocarina",
        "Akantor Dark Melody",
        "Ukanlos Horned Flute",
        "Ukanlos Skysinger",
        "Orgueil the Insane",
        "Dalamadur Song",
        "Bloodied Dalamadur",
        "Fatalis Menace Lute",
        "Fatalis Menace Soul",
        "Fatalis Ancient Lute",
        "Vadya Muse",
        "Vadya Muse+",
        "Seditious Warhorn",
        "Maqam Sedition",
        "Clemency's Peal",
        "Onyx Terpsichore",
        "Glass Royale",
        "Queen's Flute",
        "Handmade Frog",
        "Hunter Master",
        "Emperor's Speech",
        "DUMMY",
        "DUMMY",
        "Scorpion Lute",
        "Endless Loop",
        "Sonic Glass (red)",
        "Sonic Glass (yellow)",
        "Sonic Glass (green)",
        "Sonic Glass (blue)",
        "Sonic Glass (purple)",
        "Hidden Harmonic (red)",
        "Hidden Harmonic (yellow)",
        "Hidden Harmonic (green)",
        "Hidden Harmonic (blue)",
        "Hidden Harmonic (purple)"
    }; const wxArrayString wxHH_LIST(185, HH_LIST);

    const char *IG_LIST[] = {
        "(None)",
        "Bone Staff",
        "Bone Staff+",
        "Bone Glaive",
        "Bone Glaive+",
        "Aerial Glaive",
        "Sturdy Glaive",
        "Sturdy Glaive+",
        "Sturdy Glaive Redux",
        "Stealth Glaive",
        "Stealth Glaive+",
        "Stealth Glaive Redux",
        "Shadow Walker",
        "Assault Glaive",
        "Assault Glaive+",
        "Forewalker",
        "Leumundslist",
        "Leumundsgift",
        "Leumundsbruch",
        "Le Traqueur",
        "Indigo Flash",
        "Azure Bolt",
        "Verdant Levin",
        "Violindigo Hail",
        "Violazure Sleet",
        "Violverdant Glaze",
        "Heaven's Rath Glaive",
        "Rathful Blaze Glaive",
        "Unprecedented Rath",
        "Metal Mauler",
        "Metal Mauler+",
        "Metalmangler",
        "Direspike Display",
        "Direspike Display+",
        "The Harmonious Stave",
        "Fatalis Glaive",
        "Fatalis Glaive+",
        "Fatalis Fate",
        "dummy38",
        "Sky-high Glaive",
        "Highest of Glaives",
        "Deep Blue Glaive",
        "Midnight Glaive",
        "Mind Stick",
        "Mind Stick Stone",
        "Mind Stick Rock",
        "Mind Stick Mount",
        "Mind Stick Wizard",
        "Mind Stick Wonder",
        "Mind Stick Demon",
        "Mind Stick Fiend",
        "Shell Intoner",
        "Shell Intoner+",
        "Crab Intoner",
        "Purple Intoner",
        "Hermit Scissors",
        "Spirit Eater",
        "Reaper's Stroke",
        "Silent Eye",
        "Silent Eye+",
        "Nightmare",
        "Needle Ivy",
        "Needle Ivy+",
        "Needle Vine",
        "Paralyzing Vine",
        "Medusa",
        "Medusa+",
        "Medusa Mirror",
        "Névé Rod",
        "Névé Rod+",
        "Névé Frost",
        "Fimbulvetr",
        "Sand Fauchard",
        "Sand Fauchard+",
        "Iörovellir",
        "Sect Happa",
        "Sect Happa+",
        "Trim Happa",
        "Cannibal Happa",
        "Diablos Rod",
        "Diablos Rod+",
        "Tyrant Rod",
        "Thanatos Rod",
        "Thanatos Rod+",
        "Anubis",
        "La Merveille",
        "Le Miracle",
        "List/Confiance",
        "Bruch/Logique",
        "Wehmut/Merveille",
        "Boltbrute",
        "King Boltbrute",
        "Emperor Boltbrute",
        "Icephantom",
        "Propagation",
        "Blossomajesty",
        "Universus",
        "Metalmangler+",
        "Demonlord Cudgel",
        "Demonlord Grudgel",
        "Self-possession",
        "Dalamadur Scepter",
        "Bounding Dalamadur",
        "Dios Rod",
        "Demolition Press",
        "Quantum Demolisher",
        "Lightbreak Press",
        "Ukanlos Staff",
        "Ukanlos Staff+",
        "Ukanlos Skytraveler",
        "Daora's Entom",
        "Daora's Tethidine",
        "Daora's Samudra",
        "Eldaora's Entom",
        "Eldaora's Tethidine",
        "Eldaora's Samudra",
        "Caster's Rod",
        "Caster's Rod+",
        "Hazy Caster",
        "True Fatalis Dyaus",
        "Hellruin Glaive",
        "Hellruin Glaive Gift""",
        "Hellruin Glaive Omen""",
        "Fatalis Soldier",
        "Fatalis Enforcer",
        "Fatalis Overlord",
        "Altair",
        "Altair+",
        "Seditious Breaker",
        "Lana Sedition",
        "Messenger's Mark",
        "Luminary's Mark",
        "Limbo Lacrimosa",
        "Clockwork",
        "dummy134",
        "dummy135",
        "dummy136",
        "dummy137",
        "Bone Staff (red)",      // 138
        "Bone Staff (yellow)",
        "Bone Staff (green)",
        "Bone Staff (blue)",
        "Bone Staff (purple)",
        "Metal Mauler (red)",
        "Metal Mauler (yellow)",
        "Metal Mauler (green)",
        "Metal Mauler (blue)",
        "Metal Mauler (purple)",
        "Leumundslist (red)",
        "Leumundslist (yellow)",
        "Leumundslist (green)",
        "Leumundslist (blue)",
        "Leumundslist (purple)",
        "Sect Happa (red)",
        "Sect Happa (yellow)",
        "Sect Happa (green)",
        "Sect Happa (blue)",
        "Sect Happa (purple)",         // 157
        "Dancing Mad",
        "Hades Shinerod"
    }; const wxArrayString wxIG_LIST(160, IG_LIST);

    const char *CB_LIST[] = {
        "(None)",
        "Elite Blade",
        "Elite Blade+",
        "Defender's Blade",
        "Kaiser Blade",
        "Blackguard",
        "Full Blackguard",
        "Sentinel Blade",
        "Sentinel Blade+",
        "Noblest of Lieges",
        "Dear Lutemis",
        "Dear Lutemia",
        "Dear Hecatel",
        "Dear Hecatelia",
        "Axelion Blade",
        "Halberion Blade",
        "Bardichion Blade",
        "Hellsire Blade",
        "Hellspawn Blade",
        "Guardsqual",
        "Guardsqual+",
        "Squaliarma",
        "Squaliarmada",
        "Elendskraft",
        "Leidenskraft",
        "Unheilskraft",
        "L'Oppresseur",
        "Deceadeus",
        "Heroic Deceadeus",
        "Permanence",
        "Izanami",
        "Fatalis Charger",
        "Ruiner Reaver",
        "Starlight Axe",
        "Grandstar Axe",
        "dummy35",
        "dummy36",
        "Full Blackguard+",
        "Schwarzschild",
        "K. Captain's Blade",
        "Die Walküre",
        "Arachnoscale",
        "Arachnoscale+",
        "Arachnoscythe",
        "Belobog's Scythe",
        "Schwarzschlum",
        "Schwarzschlum+",
        "Chernobog's Scythe",
        "Schildsect",
        "Schildsect+",
        "Galvanisect",
        "Dominisect",
        "Maximinsect",
        "Dear Rose",
        "Dear Rosetta",
        "Luna Eostre",
        "Azure Swallow",
        "Azure Skylark",
        "Rathflame Ubernova",
        "Blossomauler",
        "Propensity",
        "Serrated Glace",
        "Trios Tristesse",
        "The Haboob",
        "Desert Rose",
        "L'Essor",
        "Le Salut",
        "Elends/Essor",
        "Diablos Strongarm",
        "Cera Cediment",
        "Ceadeus Regalia",
        "Kyusen",
        "Watatsumi",
        "Daora's Casca",
        "Daora's Thwartoise",
        "Eldaora Casca",
        "Teostra's Striker",
        "Teostra's Nova",
        "Dios Strongarm",
        "Demolition C. Blade",
        "Fulgent Demolisher",
        "Lightbreak C. Blade",
        "Demonlord C. Blade",
        "Demonlord Supersurge",
        "Akantor C. Blade",
        "Akantor Severance",
        "Bebladed Implement",
        "Machina Razer",
        "Adélie the Savior",
        "Dalamadur C. Blade",
        "Patient Dalamadur",
        "True Fatalis Charger",
        "True Ruiner Reaver",
        "Fatalis Mien",
        "Aslat Charger",
        "Aslat Charger+",
        "Seditious C. Blade",
        "Garuda Sedition",
        "Forbidden Coffin",
        "Promised Nadir",
        "dummy100",
        "DUMMY",
        "DUMMY",
        "Awaritia",
        "Fallen Morgenröte",
        "Elite Blade (red)",
        "Elite Blade (yellow)",
        "Elite Blade (green)",
        "Elite Blade (blue)",
        "Elite Blade (purple)",
        "Dear Lutemis (red)",
        "Dear Lutemis (yellow)",
        "Dear Lutemis (green)",
        "Dear Lutemis (blue)",
        "Dear Lutemis (purple)",
        "Elendskraft (red)",
        "Elendskraft (yellow)",
        "Elendskraft (green)",
        "Elendskraft (blue)",
        "Elendskraft (purple)",
        "Deceadeus (red)",
        "Deceadeus (yellow)",
        "Deceadeus (green)",
        "Deceadeus (blue)",
        "Deceadeus (purple)",
    }; const wxArrayString wxCB_LIST(125, CB_LIST);
}
#endif