#ifndef __DecryptFrameParser__
#define __DecryptFrameParser__

/**
@file
Subclass of DecryptFrame, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"

//// end generated include

/** Implementing DecryptFrame */
class DecryptFrameParser : public DecryptFrame
{
	protected:
		// Handlers for DecryptFrame events.
	virtual void OnDecSave(wxFileDirPickerEvent& event) override;
	virtual void OnDecQuest(wxFileDirPickerEvent& event) override;
public:
	/** Constructor */
	DecryptFrameParser( wxWindow* parent );
//// end generated class members

};

#endif // __DecryptFrameParser__
