#ifndef __EqEditorParser__
#define __EqEditorParser__

/**
@file
Subclass of EqEditor, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"

//// end generated include

/** Implementing EqEditor */
class EqEditorParser : public EqEditor
{
protected:
    // Handlers for EqEditor events.
    virtual void OnChoiceChange(wxCommandEvent& event) override;
    virtual void OnNameChoiceChange(wxCommandEvent& event) override;

public:
    /** Constructor */
    EqEditorParser(wxWindow* parent);
    //// end generated class members
    void	PopulateData();

    int		        currentID;
    int             currentType;
    int             currentName;
};

#endif // __EqEditorParser__
