#ifndef __GSpanelParser__
#define __GSpanelParser__

/**
@file
Subclass of GSpanel, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"
#include "EqEditorParser.h"

//// end generated include

/** Implementing GSpanel */
class GSpanelParser : public GSpanel
{
    protected:
        virtual void OnCopy(wxCommandEvent& event) override;
        virtual void OnPaste(wxCommandEvent& event) override;
        virtual void OnSave(wxCommandEvent& event) override;
        virtual void OnStatusTypeChange(wxCommandEvent& event) override;

	public:
		/** Constructor */
		GSpanelParser( wxWindow* parent );
	//// end generated class members
        void	PopulateData();
        void	ParseData();
        void	SaveData();


        int		itemID;
    private:
        EqEditorParser* MainEditor;
};

#endif // __GSpanelParser__
