#ifndef __LBGtable_0F_Parser__
#define __LBGtable_0F_Parser__

/**
@file
Subclass of LBGtable_0F_, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"

//// end generated include

/** Implementing LBGtable_0F_ */
class LBGtable_0F_Parser : public LBGtable_0F_
{
	public:
		/** Constructor */
		LBGtable_0F_Parser( wxWindow* parent );
	//// end generated class members
        void    Populate();

};

#endif // __LBGtable_0F_Parser__
