#ifndef __MHToolsMainFrame__
#define __MHToolsMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"
#include <wx/treelist.h>

//// end generated include

/** Implementing MainFrame */
class MHToolsMainFrame : public MainFrame
{
protected:
	virtual void OnMH4U(wxCommandEvent& event) override;
	virtual void OnTests(wxCommandEvent& event) override;
	virtual void OnModdingTools(wxCommandEvent& event) override;
	virtual void OnItemSelect(wxTreeListEvent& event) override;
	virtual void OnOpenSelected(wxCommandEvent& event) override;
	virtual void OnDecrypt(wxCommandEvent& event) override;
	
	static	wxTreeListItem*	mh3uSave;
	static	wxTreeListItem*	mh3uQuest;
	static	wxTreeListItem*	mh4uSave;
	static	wxTreeListItem*	mh4uQuest;
	static	wxTreeListItem*	mhxxSave;
	static	wxTreeListItem*	mhxxQuest;
	
public:
	MHToolsMainFrame( wxWindow* parent );
	
	virtual void AppendItm(const wxArrayString& filenames);

};


class DnDFile : public wxFileDropTarget
{
public:
	DnDFile(wxTreeListCtrl *pOwner = NULL);

	virtual bool OnDropFiles(wxCoord x,
		wxCoord y,
		const wxArrayString& filenames) wxOVERRIDE;

private:
	wxTreeListCtrl *m_pOwner;
};

#endif // __MHToolsMainFrame__