#ifndef __MHToolsTestsPanel__
#define __MHToolsTestsPanel__

/**
@file
Subclass of TestsPanel, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"

//// end generated include

/** Implementing TestsPanel */
class MHToolsTestsPanel : public TestsPanel
{
protected:
	// Handlers for TestsPanel events.
	virtual void OnGRIDTest( wxCommandEvent& event ) override;
	virtual void OnHTTPTest( wxCommandEvent& event ) override;
	virtual void OnPNGtest( wxCommandEvent& event ) override;
public:
	/** Constructor */
	MHToolsTestsPanel( wxWindow* parent );
//// end generated class members

};

#endif // __MHToolsTestsPanel__
