#ifndef __PNGtestPanelParser__
#define __PNGtestPanelParser__

/**
@file
Subclass of PNGtestPanel, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"

//// end generated include

/** Implementing PNGtestPanel */
class PNGtestPanelParser : public PNGtestPanel
{
protected:
	virtual void OnAppendStrImg(wxCommandEvent& event) override;
	wxBitmap	CreateBitmap(const wxColour& colour);
	virtual void OnAppendIcons(wxCommandEvent& event) override;
	virtual void OnReset(wxCommandEvent& event) override;
	virtual void BtnOnFit(wxCommandEvent& event) override;
	
	static wxBitmap* image;
public:
	/** Constructor */
	PNGtestPanelParser( wxWindow* parent );
//// end generated class members
void	Populate();
};

#endif // __PNGtestPanelParser__
