#ifndef __SApanelParser__
#define __SApanelParser__

/**
@file
Subclass of SApanel, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"
#include "EqEditorParser.h"

//// end generated include

/** Implementing SApanel */
class SApanelParser : public SApanel
{
	protected:
		// Handlers for SApanel events.
		void OnStatusTypeChange( wxCommandEvent& event ) override;
		void OnCopy( wxCommandEvent& event ) override;
		void OnPaste( wxCommandEvent& event ) override;
		void OnSave( wxCommandEvent& event ) override;
	public:
		/** Constructor */
		SApanelParser( wxWindow* parent );
	//// end generated class members
        void	PopulateData();
        void	ParseData();
        void	SaveData();


        int		itemID;
    private:
        EqEditorParser* MainEditor;

};

#endif // __SApanelParser__
