#ifndef __SaveEditorFrame__
#define __SaveEditorFrame__

/**
@file
Subclass of SaveEditorFrame, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"

//// end generated include

/** Implementing SaveEditorFrame */
class SaveEditorFrameParser : public SaveEditorFrame
{
protected:
	// Handlers for SaveEditorFrame events.
	virtual void OnFileSave( wxCommandEvent& event ) override;
	virtual void ItemEditOnShowReadID(wxCommandEvent& event) override;
	virtual void ItemEditCboxOnItemSelect(wxCommandEvent& event) override;
	virtual void ItemEditCboxOnPressEnter(wxCommandEvent& event) override;
	virtual void ItemEditOnItemListSelectionChange(wxDataViewEvent& event) override;
	virtual void EqEditOnShowReadID(wxCommandEvent& event) override;
	virtual void EqEditOnEditButton(wxCommandEvent& event) override;
	virtual void EqEditOnCopyButton(wxCommandEvent& event) override;
	virtual void EqEditOnEqListSelectionChange(wxDataViewEvent& event) override;
	virtual void WriteGeneralData();
	
	static std::string* filename;
public:
	/** Constructor */
	SaveEditorFrameParser( wxWindow* parent );
	virtual void ParseData(std::string* fname);

};

#endif // __SaveEditorFrame__
