#ifndef __TalismanPanelParser__
#define __TalismanPanelParser__

/**
@file
Subclass of TalismanPanel, which is generated by wxFormBuilder.
*/

#include "..\wxGUI.h"
#include "EqEditorParser.h"

//// end generated include

/** Implementing TalismanPanel */
class TalismanPanelParser : public TalismanPanel
{
	protected:
		// Handlers for TalismanPanel events.
		virtual void OnCopy( wxCommandEvent& event ) override;
        virtual void OnPaste( wxCommandEvent& event ) override;
        virtual void OnSave( wxCommandEvent& event ) override;
	public:
		/** Constructor */
		TalismanPanelParser( wxWindow* parent );
	//// end generated class members
        void	PopulateData();
        void	ParseData();
        void	SaveData();


        int		itemID;
    private:
        EqEditorParser* MainEditor;
};

#endif // __TalismanPanelParser__
